---------------------------------Headline------------------------------
--
-- System/Module: ENABLERDB
--
-- Name:  DDL_DATA_MODEL_NOTIFICATIONS.sql
--
-- Created by              Adnane AMELLAL
-- Creation date           09/03/2025
-- Version
--
-- -- Tables impacted:
--
-- Description:
--
-- Parameters     IN:
-- Parameters    OUT:
-- Parameters IN-OUT:
--
-- Return values:
-- Error codes:
--
--------------------------------Barcode--------------------------------
CREATE USER NOTIFICATIONS IDENTIFIED BY NOTIFICATIONS DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO NOTIFICATIONS;  
GRANT RESOURCE TO NOTIFICATIONS;
ALTER USER NOTIFICATIONS QUOTA UNLIMITED ON DATA;
ALTER USER NOTIFICATIONS QUOTA UNLIMITED ON INDX;

CREATE TABLE NOTIFICATIONS.NOTIFICATIONS 
(   
  ID                 NUMBER          NOT NULL,
  NOTIFICATION_TYPE  VARCHAR2(10)    NOT NULL,
  CREATED_AT         DATE DEFAULT SYSDATE,
  SENT_AT            DATE,
  SENT_ERROR         VARCHAR2(500),
  SUBJECT            VARCHAR2(500),
  MESSAGE            VARCHAR2(2000)  NOT NULL,
  STATUS             INTEGER         NOT NULL,
  RETRIES            INTEGER,
  SENT_FROM          VARCHAR2(500),
  SENT_TO            VARCHAR2(500)   NOT NULL,
  ATTACHEMENT        VARCHAR2(2000),
  MIME_TYPE          VARCHAR2(50)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;
 
ALTER TABLE NOTIFICATIONS.NOTIFICATIONS ADD CONSTRAINT PK_NOTIFICATIONS_ID PRIMARY KEY  (ID);
 
COMMENT ON COLUMN NOTIFICATIONS.SENT_FROM  IS '- EMAIL
- SENDER'; 
COMMENT ON COLUMN NOTIFICATIONS.SENT_TO  IS '- EMAIL
- MSISDN'; 
COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_TYPE  IS '- SMS
- EMAIL'; 
COMMENT ON COLUMN NOTIFICATIONS.STATUS  IS '0 : Nouvelle NOTIFICATIONS à traiter
1 : NOTIFICATIONS envoyée avec succès
-1 : NOTIFICATIONS en erreur
';
 
CREATE INDEX NOTIFICATIONS.IDX_NOTIFICATIONS_STATUS ON NOTIFICATIONS.NOTIFICATIONS
(STATUS)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );           
           
ALTER TABLE NOTIFICATIONS.NOTIFICATIONS
    ADD (
        CONSTRAINT FK_NOTIFICATION_TYPE CHECK
            (NOTIFICATION_TYPE IN ('EMAIL', 'SMS'))
            ENABLE VALIDATE,
        CONSTRAINT FK_NOTIFICATION_STATUS CHECK
            (STATUS IN (0, 1, -1))
            ENABLE VALIDATE);
                       
           
CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATIONS FOR NOTIFICATIONS.NOTIFICATIONS;           
           
CREATE SEQUENCE NOTIFICATIONS.NOTIFICATIONS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;          
           
CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATIONS_SEQ FOR NOTIFICATIONS.NOTIFICATIONS_SEQ;

CREATE TABLE NOTIFICATIONS.NOTIFICATIONS_HISTORY 
(   
  ID                 NUMBER NOT NULL,
  NOTIFICATION_TYPE  VARCHAR2(10) NOT NULL,
  CREATED_AT         DATE DEFAULT SYSDATE,
  SENT_AT            DATE,
  SENT_ERROR         VARCHAR2(500),
  SUBJECT            VARCHAR2(500),
  MESSAGE            VARCHAR2(2000),
  STATUS             INTEGER,
  RETRIES            INTEGER,
  SENT_FROM          VARCHAR2(500),
  SENT_TO            VARCHAR2(500),
  ATTACHEMENT        VARCHAR2(2000),
  MIME_TYPE          VARCHAR2(50)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATIONS_HISTORY FOR NOTIFICATIONS.NOTIFICATIONS_HISTORY;  

CREATE TABLE NOTIFICATIONS.FP_SMS_CID
(
  CID          NUMBER,
  SENDER       VARCHAR2(10),
  INSERT_DATE  DATE                             DEFAULT SYSDATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM FP_SMS_CID FOR NOTIFICATIONS.FP_SMS_CID;

GRANT SELECT, UPDATE, DELETE, INSERT ON NOTIFICATIONS.NOTIFICATIONS TO LIQUI_DML_ROLE; 
GRANT SELECT ON NOTIFICATIONS_SEQ TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON NOTIFICATIONS.NOTIFICATIONS_HISTORY TO LIQUI_DML_ROLE; 
GRANT SELECT, UPDATE, DELETE, INSERT ON NOTIFICATIONS.FP_SMS_CID TO LIQUI_DML_ROLE; 