---------------------------------Headline------------------------------
--
-- System/Module: ENABLERDB
--
-- Name:  DDL_ENABLERDB_DATA_MODEL_DOCUMENT_FINANCE.sql
--
-- Created by              Adnane AMELLAL
-- Creation date           28/04/2025
-- Version
--
-- -- Tables impacted:
--
-- Description:
--
-- Parameters     IN:
-- Parameters    OUT:
-- Parameters IN-OUT:
--
-- Return values:
-- Error codes:
--
--------------------------------Barcode--------------------------------
CREATE USER FINANCE IDENTIFIED BY FINANCE DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO FINANCE;  
GRANT RESOURCE TO FINANCE;
ALTER USER FINANCE QUOTA UNLIMITED ON DATA;
ALTER USER FINANCE QUOTA UNLIMITED ON INDX;

CREATE TABLE FINANCE.DOCUMENT
(
	DOCUMENT_ID	  NUMBER,
	CUSTOMERID	  VARCHAR2(40)  NOT NULL,
	CUSTNUM	      VARCHAR2(30)  NOT NULL,
	DOC_TYPE	    VARCHAR2(2)   NOT NULL,
	REF_NUM	      VARCHAR2 (30) NOT NULL,
	OHXACT	      NUMBER,
	ENT_DATE	    DATE          DEFAULT SYSDATE,
	DUE_DATE	    DATE,
	DOC_AMOUNT	  FLOAT,
	OPEN_AMOUNT	  FLOAT,
	DISC_AMOUNT	  FLOAT,
	AR_GLCODE  	  VARCHAR2 (10),
	POST_PERIOD	  VARCHAR2 (6),
	POST_GL_DATE	DATE,
	GL_POST_ID	  INTEGER,
	COST_ID	      INTEGER,
	BILLING_ACCOUNT_ID	INTEGER,
	USER_ID	      VARCHAR2 (30),
	CATALOG	      VARCHAR2 (30)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.DOCUMENT ADD CONSTRAINT PK_DOCUMENT_ID PRIMARY KEY  (DOCUMENT_ID);

COMMENT ON COLUMN FINANCE.DOCUMENT.DOCUMENT_ID               IS 'ID interne du document';                                                        
COMMENT ON COLUMN FINANCE.DOCUMENT.CUSTOMERID                IS 'Customer ID au niveau du CPR';       
COMMENT ON COLUMN FINANCE.DOCUMENT.CUSTNUM                   IS 'ID publique du client EB -> ID de l''organisation sur CPR';                                                          
COMMENT ON COLUMN FINANCE.DOCUMENT.DOC_TYPE                  IS 'Type de document : Facture, avance, Avoir, Dépôt de garantie ou autres charges';
COMMENT ON COLUMN FINANCE.DOCUMENT.REF_NUM                   IS 'Numéro de référence du document';                                               
COMMENT ON COLUMN FINANCE.DOCUMENT.ENT_DATE                  IS 'Date de saisie';                                                                
COMMENT ON COLUMN FINANCE.DOCUMENT.DUE_DATE                  IS 'Date limite de paiement';                                                       
COMMENT ON COLUMN FINANCE.DOCUMENT.DOC_AMOUNT                IS 'Montant total du document';                                                     
COMMENT ON COLUMN FINANCE.DOCUMENT.OPEN_AMOUNT               IS 'Montant ouvert du document';                                                    
COMMENT ON COLUMN FINANCE.DOCUMENT.DISC_AMOUNT               IS 'Montant de la remise sur le document';                                          
COMMENT ON COLUMN FINANCE.DOCUMENT.AR_GLCODE                 IS 'Code comptable client (ACCOUNT RECEIVABLE)';                                                        
COMMENT ON COLUMN FINANCE.DOCUMENT.POST_PERIOD               IS 'Période comptable';                                                             
COMMENT ON COLUMN FINANCE.DOCUMENT.POST_GL_DATE              IS 'Date de transfert au grand livre (GL)';                                         
COMMENT ON COLUMN FINANCE.DOCUMENT.GL_POST_ID                IS 'ID de la transaction de transfert au GL';                                       
COMMENT ON COLUMN FINANCE.DOCUMENT.COST_ID                   IS 'Id du centre de coût';                                                          
COMMENT ON COLUMN FINANCE.DOCUMENT.BILLING_ACCOUNT_ID        IS 'Id du compte de facturation';                                                   
COMMENT ON COLUMN FINANCE.DOCUMENT.USER_ID                   IS 'ID de l''utilisateur';                                                           
COMMENT ON COLUMN FINANCE.DOCUMENT.CATALOG                   IS 'Catalogue source du document : RETAIL dans le cas des factures prépayées';                                     

CREATE OR REPLACE PUBLIC SYNONYM DOCUMENT FOR FINANCE.DOCUMENT;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.DOCUMENT TO LIQUI_DML_ROLE; 

CREATE TABLE FINANCE.DOCUMENT_DETAIL
(
		DOCUMENT_ID	   NUMBER,
		SEQ_ID	       NUMBER,
		PRODUCT_ID	   VARCHAR2 (32) NOT NULL,
		CO_ID   	     NUMBER,
		SNCODE  	     INTEGER,
		TMCODE  	     INTEGER,
		QUANTITY	     INTEGER       DEFAULT 1,
		UNIT_PRICE	   FLOAT         NOT NULL,
		DISCOUNT	     FLOAT         NOT NULL,
		NET_AMOUNT     FLOAT         NOT NULL,
		TAX_AMOUNT	   FLOAT         NOT NULL,
		GROSS_AMOUNT	 FLOAT         NOT NULL,
		GLCODE	       VARCHAR2 (10) NOT NULL,
		TAX_GLCODE	   VARCHAR2 (10),
		DISC_GLCODE	   VARCHAR2 (10),
		ORDER_ID	     VARCHAR2 (30)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD CONSTRAINT PK_DOCUMENT_DETAIL_ID PRIMARY KEY  (SEQ_ID, DOCUMENT_ID);

COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.DOCUMENT_ID        IS 'ID interne du document';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.PRODUCT_ID         IS 'ID du produit';       
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.QUANTITY           IS 'Quantité vendue';     
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.UNIT_PRICE         IS 'Tarif unitaire HT';   
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.DISCOUNT           IS 'Montant de la remise';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.NET_AMOUNT         IS 'Montant total HT';    
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.TAX_AMOUNT         IS 'Montant de la taxe';  
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.GROSS_AMOUNT       IS 'Montant total TTC';   
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.GLCODE             IS 'Code comptable produit';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.TAX_GLCODE         IS 'Code comptable de la taxe';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.DISC_GLCODE        IS 'Code comptable de remise';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.ORDER_ID           IS 'ID de l’ordre EOC';   

CREATE OR REPLACE PUBLIC SYNONYM DOCUMENT_DETAIL FOR FINANCE.DOCUMENT_DETAIL;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.DOCUMENT_DETAIL TO LIQUI_DML_ROLE; 

CREATE SEQUENCE FINANCE.DOCUMENT_DETAIL_SEQ_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;    
  
CREATE OR REPLACE PUBLIC SYNONYM DOCUMENT_DETAIL_SEQ_ID_SEQ FOR FINANCE.DOCUMENT_DETAIL_SEQ_ID_SEQ;
  
GRANT SELECT ON FINANCE.DOCUMENT_DETAIL_SEQ_ID_SEQ TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.PAYMENT_MODE
(
		PAY_MODE_ID 	INTEGER,
		PAY_MODE_CODE	VARCHAR2 (10) NOT NULL,
		PAY_MODE_DES	VARCHAR2 (30) NOT NULL,
		ENT_DATE	    DATE          DEFAULT SYSDATE,
		ISACTIVE	    VARCHAR2 (1),
		PAY_MODE_CAT	INTEGER,
		PRINT_FLAG	  VARCHAR2 (1)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.PAYMENT_MODE ADD CONSTRAINT PK_PAY_MODE_ID PRIMARY KEY  (PAY_MODE_ID);

COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_ID         IS 'ID interne du mode de paiement';                       
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_CODE       IS 'ID publique du mode de paiement';                      
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_DES        IS 'Description du mode de paiement';                      
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.ENT_DATE            IS 'Date de saisie';                                       
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.ISACTIVE            IS 'État du mode de paiement :
O : Actif
N : Inactif';                           
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_CAT        IS 'Catégorie du mode de paiement. CASH, CHEQ, CARD …etc.';                                   
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PRINT_FLAG          IS 'Flag d''impression du reçu de paiement';      

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_MODE FOR FINANCE.PAYMENT_MODE;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT_MODE TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.PAYMENT
(
		PAYMENT_ID	  INTEGER,
		CUSTOMER_ID	  INTEGER       NOT NULL,
		CUSTNUM	      VARCHAR2 (30) NOT NULL,
		ENT_DATE	    DATE          DEFAULT SYSDATE,
		CHK_NUM       VARCHAR2 (30) NOT NULL,
		CHK_DATE	    DATE,
		PAY_MODE_ID	  INTEGER       NOT NULL,
		AMOUNT	      FLOAT         NOT NULL,
		STATUS	      VARCHAR2 (1)  NOT NULL,
		USER_ID	      VARCHAR2 (10) NOT NULL,
		POST_GL_DATE	DATE,
		POST_PERIOD   VARCHAR2 (6)  NOT NULL,
		COST_ID	      INTEGER       NOT NULL,
		SYSTEM	      VARCHAR2 (1)  NOT NULL,
		PAY_GLCODE	  VARCHAR2 (30),
		STAMP_AMT	    FLOAT,
		BORDU_NUM	    VARCHAR2 (30),
		BANK_CODE	    VARCHAR2 (3),
		BRANCH_CODE	  VARCHAR2 (5),
		BANK_ACCNO	  VARCHAR2 (24),
		BANK_NAME	    VARCHAR2 (30),
		RIB_KEY	      VARCHAR2 (2),
		SOURCE	      VARCHAR2 (10),
		EBSYNCHED	    VARCHAR2 (1)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.PAYMENT ADD CONSTRAINT PK_PAYMENT_ID PRIMARY KEY  (PAYMENT_ID);

COMMENT ON COLUMN FINANCE.PAYMENT.PAYMENT_ID       IS 'ID interne du paiement';                                  
COMMENT ON COLUMN FINANCE.PAYMENT.CUSTOMER_ID      IS 'ID du client EB';                                         
COMMENT ON COLUMN FINANCE.PAYMENT.CUSTNUM          IS 'ID publique du client';                                   
COMMENT ON COLUMN FINANCE.PAYMENT.ENT_DATE         IS 'Date de saisie du paiement';                              
COMMENT ON COLUMN FINANCE.PAYMENT.CHK_DATE         IS 'Date de référence du paiement : Date du chèque par ex.';  
COMMENT ON COLUMN FINANCE.PAYMENT.PAY_MODE_ID      IS 'Id du mode de paiement';                                  
COMMENT ON COLUMN FINANCE.PAYMENT.AMOUNT           IS 'Montant du paiement';                                     
COMMENT ON COLUMN FINANCE.PAYMENT.STATUS           IS 'Statut du paiement :  
E : Encaissé
S : Soumis
V : Validé
D : Déposé
A : Annulé
R : Rejeté';                                  
COMMENT ON COLUMN FINANCE.PAYMENT.POST_GL_DATE     IS 'Date de transfert de la transaction au Grand Livre ';   
COMMENT ON COLUMN FINANCE.PAYMENT.POST_PERIOD      IS 'Période comptable';                                                      
COMMENT ON COLUMN FINANCE.PAYMENT.COST_ID          IS 'ID du centre de coût';                              
COMMENT ON COLUMN FINANCE.PAYMENT.SYSTEM           IS 'Type de la facture objet du paiement :
•	Prépayé
•	Postpayé
•	Fixe
•	Internet';
COMMENT ON COLUMN FINANCE.PAYMENT.PAY_GLCODE       IS 'Code comptable de l’encaissement';                               
COMMENT ON COLUMN FINANCE.PAYMENT.STAMP_AMT        IS 'Montant des droits de timbre dans le cas de paiement en Espèces';
COMMENT ON COLUMN FINANCE.PAYMENT.BORDU_NUM        IS 'Référence du bordereau de remise';                               
COMMENT ON COLUMN FINANCE.PAYMENT.BANK_CODE        IS 'Code de banque si applicable';                                   
COMMENT ON COLUMN FINANCE.PAYMENT.BRANCH_CODE      IS 'Code de l’agence bancaire';                                      
COMMENT ON COLUMN FINANCE.PAYMENT.BANK_ACCNO       IS 'Numéro du compte bancaire';                                      
COMMENT ON COLUMN FINANCE.PAYMENT.BANK_NAME        IS 'Intitulé de la banque';                                          
COMMENT ON COLUMN FINANCE.PAYMENT.RIB_KEY          IS 'Clé RIB';                                                        
COMMENT ON COLUMN FINANCE.PAYMENT.SOURCE           IS 'Payment source:
PG – Payment Gateway
EB – Ericsson Billing';
COMMENT ON COLUMN FINANCE.PAYMENT.EBSYNCHED        IS 'Flag de synchronisation du paiement avec EB';

ALTER TABLE FINANCE.PAYMENT
    ADD (
        CONSTRAINT FK_PAYMENT_PAY_MODE_ID FOREIGN KEY
            (PAY_MODE_ID)
            REFERENCES FINANCE.PAYMENT_MODE (PAY_MODE_ID)
            ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT FOR FINANCE.PAYMENT;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT TO LIQUI_DML_ROLE; 

CREATE TABLE FINANCE.PAYMENT_DETAIL
(
		PAYMENT_ID	INTEGER,
		DOCUMENT_ID	INTEGER,
		PAID_AMOUNT	FLOAT         NOT NULL,
		GLCODE	    VARCHAR2 (10) NOT NULL,
		SYSTEM	    VARCHAR2 (10),
		EXTERNAL_ID	INTEGER
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.PAYMENT_DETAIL ADD CONSTRAINT PK_PAYMENT_DETAIL_ID PRIMARY KEY  (PAYMENT_ID);

COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.PAYMENT_ID     IS 'ID interne du paiement';                       
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.DOCUMENT_ID    IS 'ID du document objet du paiement';              
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.PAID_AMOUNT    IS 'Montant payé par document';                     
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.GLCODE         IS 'Code comptable';                                
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.SYSTEM         IS 'Système ayant issu le document : Mobile, WIAM'; 
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.EXTERNAL_ID    IS 'ID du paiement sur le SI externe (EB)';

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_DETAIL FOR FINANCE.PAYMENT_DETAIL;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT_DETAIL TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.PAYMENT_STATUS
(
		PAYMENT_ID	INTEGER,
		SEQNO     	INTEGER,
		STATUS	    VARCHAR2(1),
		STATUS_DATE	DATE,
		USER_ID	    VARCHAR2 (10),
		REASON_ID	  INTEGER
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.PAYMENT_STATUS ADD CONSTRAINT PK_PAYMENT_STATUS_ID PRIMARY KEY  (PAYMENT_ID);

COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.PAYMENT_ID    IS 'ID interne du paiement';                  
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.SEQNO         IS 'Numéro de séquence du statut du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.STATUS        IS 'État du paiement';                        
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.STATUS_DATE   IS 'Date du statut';                          
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.USER_ID       IS 'User ayant modifié le statut du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.REASON_ID     IS 'Raison de rejet du paiement';

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_STATUS FOR FINANCE.PAYMENT_STATUS;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT_STATUS TO LIQUI_DML_ROLE;

CREATE SEQUENCE FINANCE.PAYMENT_STATUS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;    
 
CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_STATUS_SEQ FOR FINANCE.PAYMENT_STATUS_SEQ;
  
GRANT SELECT ON FINANCE.PAYMENT_STATUS_SEQ TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.REASON
(
		REASON_ID	    INTEGER,
		REASON_STATUS	VARCHAR2 (1),
		REASON_DES	  VARCHAR2 (50)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.REASON ADD CONSTRAINT PK_REASON_ID PRIMARY KEY  (REASON_ID);

COMMENT ON COLUMN FINANCE.REASON.REASON_ID        IS 'ID interne de la raison';   
COMMENT ON COLUMN FINANCE.REASON.REASON_STATUS    IS 'Status de la raison';
COMMENT ON COLUMN FINANCE.REASON.REASON_DES       IS 'Description de la raison';  

CREATE OR REPLACE PUBLIC SYNONYM REASON FOR FINANCE.REASON;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.REASON TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.AR_ACCOUNT 
(
		CATEGORY_ID    VARCHAR2 (10),
		AR_GLCODE      VARCHAR2 (30),
		GLADESC        VARCHAR2 (60),
		ENTRY_DATE     DATE,
		CATALOG        VARCHAR2 (10)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.AR_ACCOUNT ADD CONSTRAINT PK_AR_ACCOUNT PRIMARY KEY  (CATEGORY_ID, AR_GLCODE);

COMMENT ON COLUMN FINANCE.AR_ACCOUNT.CATEGORY_ID    IS 'Code de la catégorie (PRGCODE)'; 
COMMENT ON COLUMN FINANCE.AR_ACCOUNT.AR_GLCODE      IS 'Code comptable';                 
COMMENT ON COLUMN FINANCE.AR_ACCOUNT.GLADESC        IS 'Description du code comptable';  
COMMENT ON COLUMN FINANCE.AR_ACCOUNT.ENTRY_DATE     IS 'Date de saisie';                 
COMMENT ON COLUMN FINANCE.AR_ACCOUNT.CATALOG        IS 'Code du catalogue :            
RET dans le cas de vente RETAIL
TEL : pour le catalogue TELCO';  

CREATE OR REPLACE PUBLIC SYNONYM AR_ACCOUNT FOR FINANCE.AR_ACCOUNT;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.AR_ACCOUNT TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.GLENTRY
(
		GLENTRY_ID      INTEGER,      
		GLSEQ           INTEGER,      
		GLCODE          VARCHAR2 (30),
		POST_DATE       VARCHAR2 (60),
		POSTING_PERIOD  VARCHAR2 (6), 
		COST_ID         INTEGER,      
		TRX_TYPE        CHAR (1),     
		GLAMOUNT        FLOAT 
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.GLENTRY ADD CONSTRAINT PK_GLENTRY_ID PRIMARY KEY  (GLENTRY_ID);

COMMENT ON COLUMN FINANCE.GLENTRY.GLENTRY_ID      IS 'ID de la transaction de transfert vers le GL';
COMMENT ON COLUMN FINANCE.GLENTRY.GLSEQ           IS 'Numéro de séquence';                          
COMMENT ON COLUMN FINANCE.GLENTRY.GLCODE          IS 'Code comptable';                              
COMMENT ON COLUMN FINANCE.GLENTRY.POST_DATE       IS 'Date de transfert vers GL';                   
COMMENT ON COLUMN FINANCE.GLENTRY.POSTING_PERIOD  IS 'Période comptable';                           
COMMENT ON COLUMN FINANCE.GLENTRY.COST_ID         IS 'ID du centre de coût';                        
COMMENT ON COLUMN FINANCE.GLENTRY.TRX_TYPE        IS 'Type : Débit/Crédit';                         
COMMENT ON COLUMN FINANCE.GLENTRY.GLAMOUNT        IS 'Montant total de l''écriture comptable';  

CREATE OR REPLACE PUBLIC SYNONYM GLENTRY FOR FINANCE.GLENTRY;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.GLENTRY TO LIQUI_DML_ROLE;

CREATE SEQUENCE FINANCE.DOCUMENT_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;          
           
CREATE OR REPLACE PUBLIC SYNONYM DOCUMENT_ID_SEQ FOR FINANCE.DOCUMENT_ID_SEQ;

GRANT SELECT ON FINANCE.DOCUMENT_ID_SEQ TO LIQUI_DML_ROLE;

CREATE SEQUENCE FINANCE.GLENTRY_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;          
           
CREATE OR REPLACE PUBLIC SYNONYM GLENTRY_ID_SEQ FOR FINANCE.GLENTRY_ID_SEQ;

GRANT SELECT ON FINANCE.GLENTRY_ID_SEQ TO LIQUI_DML_ROLE;

CREATE SEQUENCE FINANCE.PAYMENT_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;          
           
CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_ID_SEQ FOR FINANCE.PAYMENT_ID_SEQ;

GRANT SELECT ON FINANCE.PAYMENT_ID_SEQ TO LIQUI_DML_ROLE;

CREATE SEQUENCE FINANCE.REF_NUM_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;    
  
GRANT SELECT ON FINANCE.REF_NUM_SEQ TO LIQUI_DML_ROLE;

CREATE OR REPLACE PUBLIC SYNONYM REF_NUM_SEQ FOR FINANCE.REF_NUM_SEQ;

CREATE OR REPLACE TRIGGER FINANCE.TRG_DOCUMENT_REF_NUM
BEFORE INSERT ON FINANCE.DOCUMENT
FOR EACH ROW
BEGIN
	IF :NEW.CATALOG = 'RET' THEN
	  IF :NEW.REF_NUM IS NULL THEN
	    :NEW.REF_NUM := 'RET' || LPAD(REF_NUM_SEQ.NEXTVAL, 15, '0');
	  END IF;
	END IF;
END;
/

CREATE TABLE FINANCE.TRANSACTION_TYPE 
(
		TRX_ID               INTEGER,      
		TRX_CODE             VARCHAR2 (10),      
		TRX_DESC             VARCHAR2 (40),
		TYPE                 CHAR (1),
		DEFAULT_AMT          FLOAT, 
		ADD_TICKLER_CODE     VARCHAR2 (8),      
		CANCEL_TICKLER_CODE  VARCHAR2 (8),     
		USE_CASE_SHDES       VARCHAR2 (20) 
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.TRANSACTION_TYPE ADD CONSTRAINT PK_TRX_ID PRIMARY KEY  (TRX_ID);

COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.TRX_ID               IS 'ID du type de transaction';
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.TRX_CODE             IS 'Code du type de transaction';                          
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.TRX_DESC             IS 'Libellé du type de transaction';                              
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.TYPE                 IS 'Sous type : A pour avance.';                   
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.DEFAULT_AMT          IS 'Montant par défaut dans le cas des types d’avances prédéfinies';                           
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.ADD_TICKLER_CODE     IS 'Code du mémo système correspondant';                        
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.CANCEL_TICKLER_CODE  IS 'Code du mémo système correspondant dans le cas d’annulation';                         
COMMENT ON COLUMN FINANCE.TRANSACTION_TYPE.USE_CASE_SHDES       IS 'SHDES du type de transaction EB (Paiement de facture, Paiement d''avance, paiement de garantie …etc.)';  

CREATE OR REPLACE PUBLIC SYNONYM TRANSACTION_TYPE FOR FINANCE.TRANSACTION_TYPE;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.TRANSACTION_TYPE TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.BANK 
(
		BANK_ID              NUMBER,      
		BANK_CODE            VARCHAR2 (3) UNIQUE NOT NULL,      
		BANK_NAME            VARCHAR2 (40)  NOT NULL 
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.BANK ADD CONSTRAINT PK_BANK_ID PRIMARY KEY  (BANK_ID);

COMMENT ON COLUMN FINANCE.BANK.BANK_ID               IS 'ID interne de la table';
COMMENT ON COLUMN FINANCE.BANK.BANK_CODE             IS 'Code banque';                          
COMMENT ON COLUMN FINANCE.BANK.BANK_NAME             IS 'Nom de la banque';                              

CREATE OR REPLACE PUBLIC SYNONYM BANK FOR FINANCE.BANK;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.BANK TO LIQUI_DML_ROLE;

CREATE TABLE FINANCE.BANK_BRANCH 
(
		BRANCH_ID            NUMBER,
		BANK_ID              NUMBER,      
		BRANCH_CODE          VARCHAR2 (3)  NOT NULL,      
		BRANCH_NAME          VARCHAR2 (40) NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

ALTER TABLE FINANCE.BANK_BRANCH ADD CONSTRAINT PK_BRANCH_ID PRIMARY KEY  (BRANCH_ID);

COMMENT ON COLUMN FINANCE.BANK_BRANCH.BRANCH_ID               IS 'ID interne de la table';
COMMENT ON COLUMN FINANCE.BANK_BRANCH.BANK_ID                 IS 'ID de la banque mère';
COMMENT ON COLUMN FINANCE.BANK_BRANCH.BRANCH_CODE             IS 'Code agence bancaire';                          
COMMENT ON COLUMN FINANCE.BANK_BRANCH.BRANCH_NAME             IS 'Nom de l''agence bancaire';                              

CREATE OR REPLACE PUBLIC SYNONYM BANK_BRANCH FOR FINANCE.BANK_BRANCH;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.BANK_BRANCH TO LIQUI_DML_ROLE;