---------------------------------Headline------------------------------
-- System/Module : 			ENABLERDB
-- Script Name   : 			Environnement_Spring_5.0.sql
-- Created by    :     	Adnane AMELLAL
-- Creation date : 			24/01/2025
--    
-- Modified by        
-- Modification date    
-- Modification Reason 
--        
-- Version          1.0                
-- DELIVERY 	    	
-- Tables impacted  
--
-- Description:
--
-- Parameters     IN 
--------------------------------Barcode--------------------------------
CREATE USER INTERFACE IDENTIFIED BY INTERFACE DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO INTERFACE;  
GRANT RESOURCE TO INTERFACE;
ALTER USER INTERFACE QUOTA UNLIMITED ON DATA;
ALTER USER INTERFACE QUOTA UNLIMITED ON INDX;

CREATE TABLE INTERFACE.BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID NUMBER NOT NULL PRIMARY KEY,
    VERSION NUMBER,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_INSTANCE FOR INTERFACE.BATCH_JOB_INSTANCE;

CREATE TABLE INTERFACE.BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID NUMBER NOT NULL PRIMARY KEY,
    VERSION NUMBER,
    JOB_INSTANCE_ID NUMBER NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_EXEC_INST_FK FOREIGN KEY (JOB_INSTANCE_ID)
    REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_EXECUTION FOR INTERFACE.BATCH_JOB_EXECUTION;

CREATE TABLE INTERFACE.BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID NUMBER NOT NULL,
    TYPE_CD VARCHAR(6) NOT NULL,
    KEY_NAME VARCHAR(100) NOT NULL,
    STRING_VAL VARCHAR(250),
    DATE_VAL TIMESTAMP,
    LONG_VAL NUMBER,
    DOUBLE_VAL DOUBLE PRECISION,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_EXECUTION_PARAMS FOR INTERFACE.BATCH_JOB_EXECUTION_PARAMS;

CREATE TABLE INTERFACE.BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID NUMBER NOT NULL PRIMARY KEY,
    VERSION NUMBER NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID NUMBER NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(10),
    COMMIT_COUNT NUMBER,
    READ_COUNT NUMBER,
    WRITE_COUNT NUMBER,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    CONSTRAINT STEP_EXEC_JOB_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_STEP_EXECUTION FOR INTERFACE.BATCH_STEP_EXECUTION;

CREATE TABLE INTERFACE.BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID NUMBER NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500),
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
    REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_STEP_EXECUTION_CONTEXT FOR INTERFACE.BATCH_STEP_EXECUTION_CONTEXT;

CREATE TABLE INTERFACE.BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID NUMBER NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500),
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_EXECUTION_CONTEXT FOR INTERFACE.BATCH_JOB_EXECUTION_CONTEXT;

CREATE SEQUENCE INTERFACE.BATCH_JOB_INSTANCE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_INSTANCE_SEQ FOR INTERFACE.BATCH_JOB_INSTANCE_SEQ;  

CREATE SEQUENCE INTERFACE.BATCH_JOB_EXECUTION_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_INSTANCE_SEQ FOR INTERFACE.BATCH_JOB_INSTANCE_SEQ;  

CREATE SEQUENCE INTERFACE.BATCH_STEP_EXECUTION_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE OR REPLACE PUBLIC SYNONYM BATCH_STEP_EXECUTION_SEQ FOR INTERFACE.BATCH_STEP_EXECUTION_SEQ;  

CREATE SEQUENCE INTERFACE.BATCH_STEP_EXECUTION_CONTEXT_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE OR REPLACE PUBLIC SYNONYM BATCH_STEP_EXECUTION_CONTEXT_SEQ FOR INTERFACE.BATCH_STEP_EXECUTION_CONTEXT_SEQ;  

CREATE SEQUENCE INTERFACE.BATCH_JOB_EXECUTION_CONTEXT_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE PUBLIC SYNONYM BATCH_JOB_EXECUTION_CONTEXT_SEQ FOR INTERFACE.BATCH_JOB_EXECUTION_CONTEXT_SEQ;

GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_EXECUTION TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_EXECUTION_CONTEXT TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_EXECUTION_PARAMS TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_INSTANCE TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_STEP_EXECUTION TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_STEP_EXECUTION_CONTEXT TO LIQUI_DML_ROLE;
 
GRANT SELECT ON INTERFACE.BATCH_STEP_EXECUTION_CONTEXT_SEQ TO LIQUI_DML_ROLE;
GRANT SELECT ON INTERFACE.BATCH_STEP_EXECUTION_SEQ TO LIQUI_DML_ROLE;
GRANT SELECT ON INTERFACE.BATCH_JOB_EXECUTION_SEQ TO LIQUI_DML_ROLE;
GRANT SELECT ON INTERFACE.BATCH_JOB_INSTANCE_SEQ TO LIQUI_DML_ROLE;
