
DECLARE
   nBATCHCOUNT   NUMBER;
   nBATCHNAME    VARCHAR2(16) :='MOPLISTENER';
   nBATCHDESC    VARCHAR2(64) :='MOPLISTENER';
   nBATCHVERSION VARCHAR2(100):='1.0';
BEGIN
   -- check first if an entry is already inserted
   SELECT COUNT(1) INTO nBATCHCOUNT
    FROM  DBA_USERS
    WHERE USERNAME = nBATCHNAME;

    IF nBATCHCOUNT = 0 THEN
      EXECUTE IMMEDIATE ('CREATE USER '||NBATCHNAME||' IDENTIFIED BY MOPLISTENER DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP');
      EXECUTE IMMEDIATE ('GRANT CONNECT                                           TO '||NBATCHNAME);

      DBMS_OUTPUT.PUT_LINE(nBATCHNAME||': successfully created as an ORACLE user.');
    ELSE
       DBMS_OUTPUT.PUT_LINE(nBATCHNAME||': already existed as an ORACLE user.');
    END IF;

END;
/
