---------------------------------Headline------------------------------
--
-- System/Module: EB AND ENABLERDB
--
-- Name:  DDL_DATA_MODEL_INTERFACE.sql
--
-- Created by              Adnane AMELLAL
-- Creation date           16/02/2025
-- Version
--
-- -- Tables impacted:
--
-- Description:
--
-- Parameters     IN:
-- Parameters    OUT:
-- Parameters IN-OUT:
--
-- Return values:
-- Error codes:
--
--------------------------------Barcode--------------------------------
CREATE USER LIQUIBASE
  IDENTIFIED BY LIQUIBASE
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 5 Roles for LIQUIBASE 
GRANT BSCS_ROLE TO LIQUIBASE;
GRANT CONNECT TO LIQUIBASE;
GRANT LIQUI_DML_ROLE TO LIQUIBASE;
GRANT RESOURCE TO LIQUIBASE;
ALTER USER LIQUIBASE DEFAULT ROLE ALL;

-- 1 System Privilege for LIQUIBASE 
GRANT UNLIMITED TABLESPACE TO LIQUIBASE;

-- 2 Tablespace Quotas for LIQUIBASE 
ALTER USER LIQUIBASE QUOTA UNLIMITED ON DATA;
ALTER USER LIQUIBASE QUOTA UNLIMITED ON INDX;

-- Roles LIQUI_DML_ROLE
CREATE ROLE LIQUI_DML_ROLE NOT IDENTIFIED;

-- Grantees of LIQUI_DML_ROLE
GRANT LIQUI_DML_ROLE TO JAVASERVER;
GRANT LIQUI_DML_ROLE TO LIQUIBASE;
GRANT LIQUI_DML_ROLE TO SYS WITH ADMIN OPTION;
GRANT LIQUI_DML_ROLE TO RESOURCES;
GRANT LIQUI_DML_ROLE TO TASKMANAGER;