GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_EXECUTION TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_EXECUTION_CONTEXT TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_EXECUTION_PARAMS TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_JOB_INSTANCE TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_STEP_EXECUTION TO LIQUI_DML_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON INTERFACE.BATCH_STEP_EXECUTION_CONTEXT TO LIQUI_DML_ROLE;
 


GRANT SELECT ON  INTERFACE.BATCH_STEP_EXECUTION_SEQ  TO LIQUI_DML_ROLE;
GRANT SELECT ON  INTERFACE.BATCH_JOB_EXECUTION_SEQ TO LIQUI_DML_ROLE;
GRANT SELECT ON  INTERFACE.BATCH_JOB_SEQ TO LIQUI_DML_ROLE;