CREATE USER FP_ORDER IDENTIFIED BY FP_ORDER DEFAULT TABLESPACE EOC TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO FP_ORDER;  
GRANT RESOURCE TO FP_ORDER;
ALTER USER FP_ORDER QUOTA UNLIMITED ON EOC;
ALTER USER FP_ORDER QUOTA UNLIMITED ON EOC;

CREATE TABLE FP_ORDER.ORDERQUEUE
(
  ORDER_ID       VARCHAR2(30 BYTE)              NOT NULL,
  INSTANCE_ID    VARCHAR2(50 BYTE),
  PARENT         VARCHAR2(30 BYTE),
  INSERT_DATE    DATE,
  LAST_MOD_DATE  DATE,
  SEND_DATE      DATE,
  RESPONSE_DATE  DATE,
  STATUS         VARCHAR2(10 BYTE),
  RETRY_COUNT    INTEGER,
  ACTION_DATE    DATE,
  ERROR_CODE     VARCHAR2(10 BYTE),
  ERROR_MESSAGE  VARCHAR2(200 BYTE),
  SWITCH_ID      VARCHAR2(10 BYTE),
  SENTEDIF       VARCHAR2(3000 BYTE),
  RECEIVEDIF     VARCHAR2(3000 BYTE),
  NOTIFIED       VARCHAR2(1 BYTE),
  REQUESTID      VARCHAR2(14 BYTE),
  NET_PRIORITY   VARCHAR2(1 BYTE),
  BYPASSED		   VARCHAR2(1 BYTE)
)
TABLESPACE EOC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM ORDERQUEUE FOR FP_ORDER.ORDERQUEUE;

CREATE SEQUENCE FP_ORDER.EDIFACT_SEQ
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  CYCLE
  CACHE 10
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;
  
CREATE OR REPLACE PUBLIC SYNONYM EDIFACT_SEQ FOR FP_ORDER.EDIFACT_SEQ;  

CREATE TABLE FP_ORDER.XEV25DATA
(
    REQUESTID         VARCHAR2 (14 BYTE) NOT NULL,
    MSISDN            VARCHAR2 (30 BYTE),
    ACTION            VARCHAR2 (30 BYTE),
    TMCODE            VARCHAR2 (30 BYTE),
    OCSID             VARCHAR2 (30 BYTE),
    FORFAIT           VARCHAR2 (30 BYTE),
    TMC               VARCHAR2 (30 BYTE),
    VOLUME            VARCHAR2 (30 BYTE),
    TM                VARCHAR2 (30 BYTE),
    NOMBRESMS         VARCHAR2 (30 BYTE),
    AMOUNT            VARCHAR2 (30 BYTE),
    ORIACCOUNTTYPE    VARCHAR2 (30 BYTE),
    DESACCOUNTTYPE    VARCHAR2 (30 BYTE),
    IMSI              VARCHAR2 (30 BYTE),
    RN                VARCHAR2 (30 BYTE)
)
TABLESPACE EOC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM XEV25DATA FOR FP_ORDER.XEV25DATA;

CREATE TABLE FP_ORDER.ORDERQUEUE_HIST
(
  ORDER_ID       VARCHAR2(30 BYTE)              NOT NULL,
  INSTANCE_ID    VARCHAR2(50 BYTE),
  PARENT         VARCHAR2(30 BYTE),
  INSERT_DATE    DATE,
  LAST_MOD_DATE  DATE,
  SEND_DATE      DATE,
  RESPONSE_DATE  DATE,
  STATUS         VARCHAR2(10 BYTE),
  RETRY_COUNT    INTEGER,
  ACTION_DATE    DATE,
  ERROR_CODE     VARCHAR2(10 BYTE),
  ERROR_MESSAGE  VARCHAR2(200 BYTE),
  SWITCH_ID      VARCHAR2(10 BYTE),
  SENTEDIF       VARCHAR2(3000 BYTE),
  RECEIVEDIF     VARCHAR2(3000 BYTE),
  NOTIFIED       VARCHAR2(2 BYTE),
  REQUESTID      VARCHAR2(14 BYTE),
  NET_PRIORITY   VARCHAR2(1 BYTE),
  BYPASSED		   VARCHAR2(1 BYTE)
)
TABLESPACE EOC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM ORDERQUEUE_HIST FOR FP_ORDER.ORDERQUEUE_HIST;

CREATE INDEX FP_ORDER.IDX_ORDER_REQ
ON FP_ORDER.ORDERQUEUE (REQUESTID, ORDER_ID)
NOLOGGING
TABLESPACE EOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );    

CREATE INDEX FP_ORDER.IDX_ORDER_HIST_REQ
ON FP_ORDER.ORDERQUEUE_HIST (REQUESTID, ORDER_ID)
NOLOGGING
TABLESPACE EOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );    

CREATE INDEX FP_ORDER.IDX_XEV25DATA_REQ
ON FP_ORDER.XEV25DATA (REQUESTID)
NOLOGGING
TABLESPACE EOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );    