---------------------------------Headline------------------------------
-- System/Module : 			ENABLERDB
-- Script Name   : 			DDL_PORTABILITY_NEW_DATA_MODEL.sql
-- Created by    :     	Adnane AMELLAL
-- Creation date : 			26/01/2025
--    
-- Modified by        
-- Modification date    
-- Modification Reason 
--        
-- Version          1.0                
-- DELIVERY 	    	
-- Tables impacted  
--
-- Description:
--
-- Parameters     IN 
--------------------------------Barcode--------------------------------
DECLARE
  startValue NUMBER;
BEGIN
  SELECT MOP.SEMA_MOP_TRACE_SEQ.NEXTVAL INTO startValue FROM DUAL;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOP.NP_RESOURCE_TRACE_SEQ
  START WITH ' || startValue ||
  'MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER';
END;

CREATE OR REPLACE PUBLIC SYNONYM NP_RESOURCE_TRACE_SEQ FOR MOP.NP_RESOURCE_TRACE_SEQ; 

DECLARE
  startValue NUMBER;
BEGIN
  SELECT MOP.NP_MOP_REQUEST_SEQ.NEXTVAL INTO startValue FROM DUAL;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOP.NP_REQUEST_SEQ
  START WITH ' || startValue ||
  'MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER';
END;

CREATE OR REPLACE PUBLIC SYNONYM NP_REQUEST_SEQ FOR MOP.NP_REQUEST_SEQ;  
  
DECLARE
  startValue NUMBER;
BEGIN
  SELECT MOP.NP_MOP_DETAIL_SEQ.NEXTVAL INTO startValue FROM DUAL;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOP.NP_REQUEST_HIST_SEQ
  START WITH ' || startValue ||
  'MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER';
END;  
  
CREATE OR REPLACE PUBLIC SYNONYM NP_REQUEST_HIST_SEQ FOR MOP.NP_REQUEST_HIST_SEQ;  
  
DECLARE
  startValue NUMBER;
BEGIN
  SELECT MOP.SEQ_RIO_REQUEST.NEXTVAL INTO startValue FROM DUAL;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOP.NP_RIO_REQUEST_SEQ
  START WITH ' || startValue ||
  'MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER';
END;    
  
CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_REQUEST_SEQ FOR MOP.NP_RIO_REQUEST_SEQ;  
  
DECLARE
  startValue NUMBER;
BEGIN
  SELECT MOP.SEQ_RIO_NOTIFICATION.NEXTVAL INTO startValue FROM DUAL;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOP.NP_RIO_NOTIFICATION_SEQ
  START WITH ' || startValue ||
  'MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER';
END;   

CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_NOTIFICATION_SEQ FOR MOP.NP_RIO_NOTIFICATION_SEQ;  
  
DROP SEQUENCE MOP.MOPFILESEQUENCE_SEQ;
DROP SEQUENCE MOP.SEMA_MOP_TRACE_SEQ;
DROP SEQUENCE MOP.NP_MOP_REQUEST_SEQ;
DROP SEQUENCE MOP.NP_MOP_DETAIL_SEQ;
DROP SEQUENCE MOP.MAIL_HANDLER_INPUT_SEQ;
DROP SEQUENCE MOP.NP_STATUS_MAPPING_SEQ;
DROP SEQUENCE MOP.SEQ_RIO_REQUEST;
DROP SEQUENCE MOP.SEQ_RIO_NOTIFICATION;  

ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN SNCODE;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN FLIN_ID;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN FLOUT_ID;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN ACTFLAG;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN PORTFLAG;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN OP_REQUEST;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN DOE;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN FU_PACK_ID;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN FLAN;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN CMSINT_REQUEST;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN CUSTCODE;
ALTER TABLE MOP.SEMA_MOP_REQUESTS DROP COLUMN AGPI;

DROP TABLE MOP.SEMA_MOP_FILE_DETAILS;
DROP TABLE MOP.SEMA_MOP_LAST_RUN;
DROP TABLE MOP.SEMA_MOP_MSISDN;
DROP TABLE MOP.SEMA_MOP_REJ_FILE;
DROP TABLE MOP.SEMA_MOP_REJ_LIGNE;
DROP TABLE MOP.NP_RETRY_PROCESS;
DROP TABLE MOP.NP_INCIDENT_CONFIG;
DROP TABLE MOP.NP_NOTIF_CONFIG;
DROP TABLE MOP.SEMA_MOP_ACTION_DELAY;
DROP TABLE MOP.SEMA_MOP_CODE_F;
DROP TABLE MOP.SEMA_MOP_PARAMETERS;
DROP TABLE MOP.SEMA_MOP_PORT_TYPE;
DROP TABLE MOP.MAIL_HANDLER_INPUT;
DROP TABLE MOP.SEMA_MOP_FILES;

ALTER TABLE MOP.NP_MOP_DETAIL	RENAME TO	NP_REQUEST_HIST	;
ALTER TABLE MOP.NP_MOP_REQUEST	RENAME TO	NP_REQUEST	;
ALTER TABLE MOP.RIO_NOTIFICATION	RENAME TO	NP_RIO_NOTIFICATION	;
ALTER TABLE MOP.RIO_REQUEST	RENAME TO	NP_RIO_REQUEST	;
ALTER TABLE MOP.RIO_REQUEST_DETAIL	RENAME TO	NP_RIO_REQUEST_DETAIL	;
ALTER TABLE MOP.RIO_REQUEST_HISTORY	RENAME TO	NP_RIO_REQUEST_HISTORY	;
ALTER TABLE MOP.SEMA_MOP_DETAILS	RENAME TO	NP_CHILD_REQUEST_HIST	;
ALTER TABLE MOP.SEMA_MOP_REQUESTS	RENAME TO	NP_CHILD_REQUEST	;
ALTER TABLE MOP.SEMA_MOP_TRACE	RENAME TO	NP_RESOURCE_TRACE	;
ALTER TABLE MOP.MAPPING_OPERATOR	RENAME TO	NP_MAPPING_OPERATOR	;
ALTER TABLE MOP.MAPPING_TYPE	RENAME TO	NP_MAPPING_TYPE	;
ALTER TABLE MOP.ROUTING_CONFIG	RENAME TO	NP_ROUTING_CONFIG	;
ALTER TABLE MOP.SEMA_MOP_HOLIDAY	RENAME TO	NP_HOLIDAY	;
ALTER TABLE MOP.SEMA_MOP_OPERATOR	RENAME TO	NP_OPERATOR	;
ALTER TABLE MOP.SEMA_MOP_REJECTION	RENAME TO	NP_REJECTION	;
ALTER TABLE MOP.SEMA_MOP_REPORT	RENAME TO	NP_REPORT	;
ALTER TABLE MOP.SEMA_MOP_REPORT_TYPE	RENAME TO	NP_REPORT_TYPE	;
ALTER TABLE MOP.SEMA_MOP_TRX_TYPE	RENAME TO	NP_TRX_TYPE	;
ALTER TABLE MOP.REPORT_META_DATA	RENAME TO	NP_REPORT_META_DATA	;
ALTER TABLE MOP.RIO_REQUEST_STATUS	RENAME TO	NP_RIO_REQUEST_STATUS	;

ALTER TABLE MOP.NP_CALL_TRACE ADD (PROCESSING_STATUS INTEGER, PROCESSING_DATE DATE);

COMMENT ON COLUMN MOP.NP_CALL_TRACE.PROCESSING_STATUS  IS '0: non encore envoyé
1: envoyé
2: en erreur';
COMMENT ON COLUMN MOP.NP_CALL_TRACE.PROCESSING_DATE    IS 'Date de traitement';

DECLARE
  startValue NUMBER;
BEGIN
  SELECT MAX(REQUEST) + 1 INTO startValue FROM NP_CHILD_REQUEST;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MOP.NP_CHILD_REQUEST_SEQ
  START WITH ' || startValue ||
  'MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  ORDER
  NOKEEP
  NOSCALE
  GLOBAL';
END;

CREATE OR REPLACE PUBLIC SYNONYM NP_CHILD_REQUEST_SEQ FOR MOP.NP_CHILD_REQUEST_SEQ;  

CREATE TABLE MOP.NP_NOTIF_CONFIG  
(   
   STATUS_CODE         VARCHAR2(30) NOT NULL,
   ID_MESSAGE          INTEGER NOT NULL,
   DESTINATION         VARCHAR2(10) NOT NULL,
   TO_CREATOR          INTEGER,
   EMAIL_ADDRESS       VARCHAR2(100),   
   STATUS              INTEGER,
   USER_LAST_MOD       VARCHAR2(50) NOT NULL,
   ENTDATE      DATE DEFAULT SYSDATE
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX MOP.PK_NP_NOTIF_CONFIG ON MOP.NP_NOTIF_CONFIG
(STATUS_CODE)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOP.NP_NOTIF_CONFIG ADD (
    CONSTRAINT FK_NP_NOTIF_CONFIG_ID_MESSAGE 
             FOREIGN KEY (ID_MESSAGE)
       REFERENCES MOP.NP_MESSAGE (ID_MESSAGE) ENABLE VALIDATE,
    CONSTRAINT FK_STATUS_CODE
             FOREIGN KEY (STATUS_CODE)
       REFERENCES MOP.NP_RESPONSE_STATUS (STATUS_CODE) ENABLE VALIDATE,       
    CONSTRAINT FK_NP_NOTIF_CONFIG_DEST CHECK (DESTINATION IN ('IAM', 'BDCPN')) ENABLE VALIDATE);
       

COMMENT ON COLUMN MOP.NP_NOTIF_CONFIG.DESTINATION  IS '-    IAM : Quand c''est CDB qui appels le webservice IAM
-    BDCPN: Quand c''est le batch responsable de la synchronisation de MOP avec la BDCPN qui appelle le webservice BDCPN.';
COMMENT ON COLUMN MOP.NP_NOTIF_CONFIG.TO_CREATOR  IS '-    1 si on doit notifier l''utilisateur MOP ayant créé la commande
-    0 dans le cas contraire';
COMMENT ON COLUMN MOP.NP_NOTIF_CONFIG.EMAIL_ADDRESS  IS 'Adresse mail à notifier';
COMMENT ON COLUMN MOP.NP_NOTIF_CONFIG.STATUS  IS '-	1 : Le mode notif est actif
-	0 : Le mode notif est désactivé';
     
CREATE OR REPLACE PUBLIC SYNONYM NP_NOTIF_CONFIG FOR MOP.NP_NOTIF_CONFIG;

GRANT DELETE, INSERT, SELECT, UPDATE ON MOP.NP_NOTIF_CONFIG TO LIQUI_DML_ROLE;

DROP TABLE MOP.NP_NOTIF_CONFIG;

CREATE TABLE MOP.NP_NOTIF_CONFIG  
(   
   STATUS_CODE         VARCHAR2(10) NOT NULL,
   ID_MESSAGE          INTEGER NOT NULL,
   DESTINATION         VARCHAR2(10) NOT NULL,
   TO_CREATOR          INTEGER,
   MAIL_SUBJECT        VARCHAR2(300),   
   MAIL_FROM           VARCHAR2(100),   
   MAIL_TO             VARCHAR2(500),
   MAIL_CONTENT        CLOB,  
   ENTDATE             DATE DEFAULT SYSDATE
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE UNIQUE INDEX MOP.PK_NP_NOTIF_CONFIG ON MOP.NP_NOTIF_CONFIG
(STATUS_CODE)
NOLOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MOP.NP_NOTIF_CONFIG ADD (
    CONSTRAINT FK_NP_NOTIF_CONFIG_ID_MESSAGE 
             FOREIGN KEY (ID_MESSAGE)
       REFERENCES MOP.NP_MESSAGE (ID_MESSAGE) ENABLE VALIDATE,       
    CONSTRAINT FK_NP_NOTIF_CONFIG_DEST CHECK (DESTINATION IN ('IAM', 'BDCPN')) ENABLE VALIDATE);
       

COMMENT ON COLUMN MOP.NP_NOTIF_CONFIG.DESTINATION  IS '-    IAM : Quand c''est CDB qui appels le webservice IAM
-    BDCPN: Quand c''est le batch responsable de la synchronisation de MOP avec la BDCPN qui appelle le webservice BDCPN.';
COMMENT ON COLUMN MOP.NP_NOTIF_CONFIG.TO_CREATOR  IS '-    1 si on doit notifier l''utilisateur MOP ayant créé la commande
-    0 dans le cas contraire';
     
CREATE OR REPLACE PUBLIC SYNONYM NP_NOTIF_CONFIG FOR MOP.NP_NOTIF_CONFIG;

GRANT DELETE, INSERT, SELECT, UPDATE ON MOP.NP_NOTIF_CONFIG TO LIQUI_DML_ROLE;

ALTER TABLE MOP.NP_REQUEST
ADD (REPLAYED VARCHAR2(1 Byte));

ALTER TABLE MOP.NP_CHILD_REQUEST
ADD (CUSTNUM VARCHAR2(30 Byte));
 
COMMENT ON COLUMN 
MOP.NP_CHILD_REQUEST.CUSTNUM IS 
'Customer code. It is used as the public key.';

CREATE OR REPLACE PUBLIC SYNONYM NP_NOTIF_CONFIG FOR MOP.NP_NOTIF_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM NP_CALL_TRACE FOR MOP.NP_CALL_TRACE;
CREATE OR REPLACE PUBLIC SYNONYM NP_CHILD_REQUEST FOR MOP.NP_CHILD_REQUEST;
CREATE OR REPLACE PUBLIC SYNONYM NP_CHILD_REQUEST_HIST FOR MOP.NP_CHILD_REQUEST_HIST;
CREATE OR REPLACE PUBLIC SYNONYM NP_HOLIDAY FOR MOP.NP_HOLIDAY;
CREATE OR REPLACE PUBLIC SYNONYM NP_IDTYPE FOR MOP.NP_IDTYPE;
CREATE OR REPLACE PUBLIC SYNONYM NP_MAPPING_OPERATOR FOR MOP.NP_MAPPING_OPERATOR;
CREATE OR REPLACE PUBLIC SYNONYM NP_MAPPING_TYPE FOR MOP.NP_MAPPING_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM NP_MESSAGE FOR MOP.NP_MESSAGE;
CREATE OR REPLACE PUBLIC SYNONYM NP_OPERATOR FOR MOP.NP_OPERATOR;
CREATE OR REPLACE PUBLIC SYNONYM NP_ORDER_TYPE FOR MOP.NP_ORDER_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM NP_PROCESS_DEADLINES FOR MOP.NP_PROCESS_DEADLINES;
CREATE OR REPLACE PUBLIC SYNONYM NP_PROCESS_TYPE FOR MOP.NP_PROCESS_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM NP_REJECTION FOR MOP.NP_REJECTION;
CREATE OR REPLACE PUBLIC SYNONYM NP_REPORT FOR MOP.NP_REPORT;
CREATE OR REPLACE PUBLIC SYNONYM NP_REPORT_META_DATA FOR MOP.NP_REPORT_META_DATA;
CREATE OR REPLACE PUBLIC SYNONYM NP_REPORT_TYPE FOR MOP.NP_REPORT_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM NP_REQUEST FOR MOP.NP_REQUEST;
CREATE OR REPLACE PUBLIC SYNONYM NP_REQUEST_HIST FOR MOP.NP_REQUEST_HIST;
CREATE OR REPLACE PUBLIC SYNONYM NP_RESOURCE_TRACE FOR MOP.NP_RESOURCE_TRACE;
CREATE OR REPLACE PUBLIC SYNONYM NP_RESPONSE_STATUS FOR MOP.NP_RESPONSE_STATUS;
CREATE OR REPLACE PUBLIC SYNONYM NP_RETRY_ENTRIES FOR MOP.NP_RETRY_ENTRIES;
CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_NOTIFICATION FOR MOP.NP_RIO_NOTIFICATION;
CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_REQUEST FOR MOP.NP_RIO_REQUEST;
CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_REQUEST_DETAIL FOR MOP.NP_RIO_REQUEST_DETAIL;
CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_REQUEST_HISTORY FOR MOP.NP_RIO_REQUEST_HISTORY;
CREATE OR REPLACE PUBLIC SYNONYM NP_RIO_REQUEST_STATUS FOR MOP.NP_RIO_REQUEST_STATUS;
CREATE OR REPLACE PUBLIC SYNONYM NP_ROUTING_CONFIG FOR MOP.NP_ROUTING_CONFIG;
CREATE OR REPLACE PUBLIC SYNONYM NP_STATUS FOR MOP.NP_STATUS;
CREATE OR REPLACE PUBLIC SYNONYM NP_STATUS_MAPPING FOR MOP.NP_STATUS_MAPPING;
CREATE OR REPLACE PUBLIC SYNONYM NP_TRX_TYPE FOR MOP.NP_TRX_TYPE;
