package com.example.soap;

import org.springframework.stereotype.Service;
import io.spring.guides.gs_producing_web_service.Country; // JAXB
import io.spring.guides.gs_producing_web_service.Currency; // import enumeration class generated by JAXB


@Service
public class CountryService {

    private final CountryRepository countryRepository;

    public CountryService(CountryRepository countryRepository) {
        this.countryRepository = countryRepository;
    }

    public Country findCountryById(Long id) {
        // On récupère l'entité JPA
        CountryEntity entity = countryRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Country not found"));

        // On crée l'objet SOAP (JAXB) à partir de l'objet JPA récupéré
        Country country = new Country();
        country.setId(entity.getId());
        country.setName(entity.getName());
        country.setPopulation(entity.getPopulation());
        country.setCapital(entity.getCapital());
        country.setCurrency(Currency.valueOf(entity.getCurrency())); // enumeration
        
        return country;
    }
}
