
-- grant

GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_SCHEMA_REGISTRY TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_TASK_TYPE TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_TASK TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_CHUNKTOTASK TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_RAW_RECORD TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_TASK_OUTPUT TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_REASON TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_STATUS TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON TASKMANAGER.TSK_PROCESSED_RECORD TO LIQUI_DML_ROLE;
