

-- Table TSK_REASON


CREATE TABLE TASKMANAGER.TSK_REASON
(
    CODE              VARCHAR2(20),
    DESCRIPTION       VARCHAR2(150)
)/*
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE*/;

ALTER TABLE TASKMANAGER.TSK_REASON ADD CONSTRAINT PK_TSK_REASON_CODE PRIMARY KEY (CODE);

CREATE OR REPLACE PUBLIC SYNONYM TSK_REASON FOR TASKMANAGER.TSK_REASON;

