-- Table TSK_TASK_OUTPUT

CREATE TABLE TASKMANAGER.TSK_TASK_OUTPUT
(
    ID              NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    TASK_ID     NUMBER,
    OUTPUT_TYPE     VARCHAR2(100),
    URLS            CLOB,
    OUTPUT_SUMMARY  CLOB
)/*
LOB (OUTPUT_SUMMARY) STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING)
LOB (URLS) STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
NOCOMPRESS
NOCACHE*/;

ALTER TABLE TASKMANAGER.TSK_TASK_OUTPUT ADD CONSTRAINT PK_TSK_TASK_OUTPUT_ID PRIMARY KEY (ID);


