
ALTER TABLE TASKMANAGER.TSK_TASK ADD CONSTRAINT PK_TSK_TASK_ID PRIMARY KEY  (ID);

CREATE OR REPLACE PUBLIC SYNONYM TSK_TASK FOR TASKMANAGER.TSK_TASK;

ALTER TABLE TASKMANAGER.TSK_TASK
    ADD (
        FOREIGN KEY
            (TASK_TYPE_ID)
            REFERENCES TASKMANAGER.TSK_TASK_TYPE (ID)
                ENABLE VALIDATE);

