-- Table TSK_RAW_RECORD

CREATE TABLE TASKMANAGER.TSK_RAW_RECORD
(
    ID               NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    CHUNK_ID         NUMBER,
    PARENT_ID        NUMBER,
    PARSED_RECORD    CLOB,
    RAW_JSON         CLOB,
    RAW_READ         VARCHAR2(255),
    STATUS           VARCHAR2(30),
    TASK_ID          NUMBER,
    TO_BE_PROCESSED  INTEGER
)/*
LOB (PARSED_RECORD) STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
LOB (RAW_JSON) STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE*/;

ALTER TABLE TASKMANAGER.TSK_RAW_RECORD ADD CONSTRAINT PK_TSK_RAW_RECORD_ID PRIMARY KEY (ID);
ALTER TABLE TASKMANAGER.TSK_RAW_RECORD ADD (
    CHECK (TO_BE_PROCESSED IN (0,1))
        ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM TSK_RAW_RECORD FOR TASKMANAGER.TSK_RAW_RECORD;
