CREATE INDEX TASKMANAGER.IDX_OUTPUT_TSK_TASK_ID ON TASKMANAGER.TSK_TASK_OUTPUT
    (TASK_ID)
    NOLOGGING
    TABLESPACE INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
    INITIAL          64K
    MINEXTENTS       1
    MAXEXTENTS       UNLIMITED
    PCTINCREASE      0
    BUFFER_POOL      DEFAULT
    );

ALTER TABLE TASKMANAGER.TSK_TASK_OUTPUT ADD (
    FOREIGN KEY (TASK_ID)
        REFERENCES TASKMANAGER.TSK_TASK (ID)
            ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM TSK_TASK_OUTPUT FOR TASKMANAGER.TSK_TASK_OUTPUT;
