CREATE TABLE FINANCE.DOCUMENT_DETAIL
(
		DOCUMENT_ID	    NUMBER(38),
		SEQ_ID	        NUMBER(38),
		PRODUCT_ID	    VARCHAR2 (32),
		CO_ID   	    NUMBER(38),
		SNCODE  	    NUMBER(38),
		TMCODE  	    NUMBER(38),
		QUANTITY	    INTEGER         DEFAULT 1,
		UNIT_PRICE	    FLOAT(126)      NOT NULL,
		DISCOUNT	    FLOAT(126),
		NET_AMOUNT      FLOAT(126)      NOT NULL,
		TAX_AMOUNT	    FLOAT(126)      NOT NULL,
		GROSS_AMOUNT    FLOAT(126)      NOT NULL,
		GLCODE	        VARCHAR2 (10)   NOT NULL,
		TAX_GLCODE	    VARCHAR2 (10),
		DISC_GLCODE	    VARCHAR2 (10)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.SEQ_ID             IS 'Numéro de séquence de l’item.
                                                                 Numéro d’ordre de l’item au sein du même document';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.DOCUMENT_ID        IS 'ID interne du document';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.PRODUCT_ID         IS 'ID du produit ECM';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.CO_ID              IS 'ID du contrat EB';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.SNCODE             IS 'ID du service EB';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.TMCODE             IS 'ID du plan tarifaire EB';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.QUANTITY           IS 'Quantité vendue';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.UNIT_PRICE         IS 'Tarif unitaire HT';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.DISCOUNT           IS 'Montant de la remise';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.NET_AMOUNT         IS 'Montant total HT';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.TAX_AMOUNT         IS 'Montant de la taxe';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.GROSS_AMOUNT       IS 'Montant total TTC';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.GLCODE             IS 'Code comptable produit';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.TAX_GLCODE         IS 'Code comptable de la taxe';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.DISC_GLCODE        IS 'Code comptable de remise';

ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD CONSTRAINT PK_DOCUMENT_DETAIL_ID PRIMARY KEY  (SEQ_ID);

ALTER TABLE FINANCE.DOCUMENT_DETAIL
    ADD (
        CONSTRAINT FK_DOCUMENT_DETAIL_DOCUMENT_ID FOREIGN KEY
            (DOCUMENT_ID)
            REFERENCES FINANCE.DOCUMENT (DOCUMENT_ID)
            ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM DOCUMENT_DETAIL FOR FINANCE.DOCUMENT_DETAIL;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.DOCUMENT_DETAIL TO LIQUI_DML_ROLE;