-- 1. Ajouter une colonne temporaire
ALTER TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
    ADD EXTERNAL_ID_TMP VARCHAR2(100 BYTE);

-- 2. Copier les données de l’ancienne colonne (conversion NUMBER → VARCHAR2)
UPDATE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
    SET EXTERNAL_ID_TMP = TO_CHAR(TRANSACTION_ID);

-- 3. Supprimer les contraintes liées à TRANSACTION_ID
ALTER TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
    DROP CONSTRAINT PK_EXT_PAYMENT_TRANSACTION;

-- 4. Supprimer l’ancienne colonne
ALTER TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
    DROP COLUMN TRANSACTION_ID;

-- 5. Renommer la colonne temporaire vers EXTERNAL_ID
ALTER TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
    RENAME COLUMN EXTERNAL_ID_TMP TO EXTERNAL_ID;

-- 6. Ajouter les nouvelles colonnes
ALTER TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
    ADD (
        INVOICE_ID VARCHAR2(100 BYTE),
        PAYMENT_ID VARCHAR2(100 BYTE)
    );
