CREATE TABLE FINANCE.SHEDLOCK (
    name VARCHAR(64) NOT NULL,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
              INITIAL          128K
              NEXT             16M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM SHEDLOCK  FOR FINANCE.SHEDLOCK;
GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.SHEDLOCK TO LIQUI_DML_ROLE;