BEGIN

INSERT INTO TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC, USE_CASE_SHDES)
     VALUES (1, 'INVPAY', 'Paiement de factures', 'CE2DD');

INSERT INTO TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC, TYPE, USE_CASE_SHDES)
     VALUES (2, 'ADVPAY', 'Avance pour paiement', 'A', 'CE2CO');

INSERT INTO TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC, USE_CASE_SHDES)
     VALUES (3, 'DEPPAY', 'Paiement de garantie', 'CE2DP');

INSERT INTO TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC, USE_CASE_SHDES)
     VALUES (4, 'ADV2DEP', 'Convertir avance en garantie', 'CO2DP');

INSERT INTO TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC, USE_CASE_SHDES)
     VALUES (5, 'DEP2ADV', 'Convertir garantie en avance', 'DP2CO');

INSERT INTO TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC, USE_CASE_SHDES)
     VALUES (6, 'CANCLPAY', 'Annuler de paiement', 'RV-CE2DD');

COMMIT;

END;
/