CREATE TABLE FINANCE.GLENTRY
(
		GLENTRY_ID      NUMBER(38) NOT NULL,
		GLSEQ           NUMBER(38),
		GLEXACT         NUMBER(38),
		GLCODE          VARCHAR2 (30),
		POST_DATE       VARCHAR2 (60),
		POSTING_PERIOD  VARCHAR2 (6),
		COST_ID         NUMBER(38),
		TRX_TYPE        CHAR (1),
		GLAMOUNT        FLOAT(126)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.GLENTRY.GLENTRY_ID      IS 'ID de la transaction de transfert vers le GL.  Il s’agit d’une séquence interne utilisée pour les paiements RETAIL et les paiements EB.';
COMMENT ON COLUMN FINANCE.GLENTRY.GLSEQ           IS 'Numéro de séquence';
COMMENT ON COLUMN FINANCE.GLENTRY.GLEXACT         IS 'Id de la transaction de transfert vers GL d’EB. Sera vide dans le cas des paiements du RETAIL.';
COMMENT ON COLUMN FINANCE.GLENTRY.GLCODE          IS 'Code comptable';
COMMENT ON COLUMN FINANCE.GLENTRY.POST_DATE       IS 'Date de transfert vers GL';
COMMENT ON COLUMN FINANCE.GLENTRY.POSTING_PERIOD  IS 'Période comptable';
COMMENT ON COLUMN FINANCE.GLENTRY.COST_ID         IS 'ID du centre de coût';
COMMENT ON COLUMN FINANCE.GLENTRY.TRX_TYPE        IS 'Type : Débit/Crédit';
COMMENT ON COLUMN FINANCE.GLENTRY.GLAMOUNT        IS 'Montant total de l''écriture comptable';

ALTER TABLE FINANCE.GLENTRY ADD CONSTRAINT PK_GLENTRY_ID PRIMARY KEY  (GLENTRY_ID, GLSEQ);

CREATE OR REPLACE PUBLIC SYNONYM GLENTRY FOR FINANCE.GLENTRY;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.GLENTRY TO LIQUI_DML_ROLE;