ALTER TABLE FINANCE.DOCUMENT ADD DEALER_NAME VARCHAR2(20);
ALTER TABLE FINANCE.DOCUMENT ADD DEALER_ID VARCHAR2 (10);
ALTER TABLE FINANCE.DOCUMENT ADD SAP_SYNCHED NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (SAP_SYNCHED IN (0, 1));

COMMENT ON COLUMN FINANCE.DOCUMENT.SAP_SYNCHED IS 'Flag indiquant l état de synchronisation avec le stock Sap';
COMMENT ON COLUMN FINANCE.DOCUMENT.DEALER_NAME IS 'Nom de l agence';
COMMENT ON COLUMN FINANCE.DOCUMENT.DEALER_ID IS 'Identifiant de l agence';
