CREATE TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION
(
  ID                 NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  TRANSACTION_ID     NUMBER,
  SOURCE_SYSTEM      VARCHAR2(50 BYTE),
  TRANSACTION_DATE   DATE DEFAULT CURRENT_TIMESTAMP,
  JSON_PAYLOAD       CLOB,
  SCHEMA_VERSION     VARCHAR2(20 BYTE),
  CREATED_AT         DATE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT         TIMESTAMP,
  STATUS             VARCHAR2(20 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
              INITIAL          128K
              NEXT             16M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;
COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.TRANSACTION_ID
    IS 'Identifiant unique de la transaction externe (clé primaire)';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.SOURCE_SYSTEM
    IS 'Système source ayant envoyé la transaction (ex: SystemA, SystemB)';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.TRANSACTION_DATE
    IS 'Date et heure réelle de la transaction (format TIMESTAMP)';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.JSON_PAYLOAD
    IS 'Payload JSON brut, validé par une contrainte JSON';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.SCHEMA_VERSION
    IS 'Version du schéma JSON pour permettre l’évolution du format';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.CREATED_AT
    IS 'Date de création de l’enregistrement dans le système';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.UPDATED_AT
    IS 'Date de la dernière mise à jour de l’enregistrement';

COMMENT ON COLUMN FINANCE.EXTERNAL_PAYMENT_TRANSACTION.STATUS
    IS 'Statut de traitement : NEW, PROCESSED, RECYCLE, REJECTED';


ALTER TABLE FINANCE.EXTERNAL_PAYMENT_TRANSACTION ADD CONSTRAINT PK_EXT_PAYMENT_TRANSACTION  PRIMARY KEY (TRANSACTION_ID) ;



CREATE OR REPLACE PUBLIC SYNONYM EXTERNAL_PAYMENT_TRANSACTION  FOR FINANCE.EXTERNAL_PAYMENT_TRANSACTION;
GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.EXTERNAL_PAYMENT_TRANSACTION TO LIQUI_DML_ROLE;