BEGIN

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(1, 'ESP', 'Espèce', 'ESP', 'Y', null, 'Y', 'P');

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(2, 'CHQH', 'Chèque hors place', 'CHQ', 'N', null, 'Y', 'B');

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(3, 'CHQ', 'Chèque', 'CHQ', 'Y', null, 'Y', 'B');

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(4, 'VIR', 'Virement', 'CHQ', 'Y', null, 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(5, 'TPE', 'TPE', 'CARD', 'Y', 'B', 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(6, 'VIN', 'Vignette', 'OTHR', 'Y', null, 'Y', 'V');

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(7, 'EFF', 'Effet de commerce', 'OTHR', 'Y', null, 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(8, 'GAB', 'GAB', 'OTHR', 'Y', 'E', 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(9, 'PAB', 'Prélèvement automatique', 'OTHR', 'Y', 'E','Y', 'D');

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(10, 'PFCG', 'PFCG', 'OTHR', 'N', 'E', 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(11, 'POL',  'Paiement en ligne', 'CARD', 'Y', 'E', 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(12, 'PBOL', 'Paiement Boutique en ligne', 'CARD', 'Y', 'E', 'N', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(13, 'COMP', 'Compensation', 'OTHR', 'N', null, 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(14, 'EREV', 'Paiement e-revendeur', 'CARD', 'Y', 'E', 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(15, 'MTCSH', 'MTCASH', 'OTHR', 'Y', 'E', 'Y', null);

INSERT INTO FINANCE.PAYMENT_MODE(PAY_MODE_ID, PAY_MODE_CODE, PAY_MODE_DES, PAY_MODE_CAT, ISACTIVE, ISEXTERNAL, PRINT_FLAG, PAYMENTCODE)
                    values(16, 'DGT', 'DIGITAL', 'OTHR', 'Y', 'E', 'N', null);

COMMIT;

END;
/