ALTER TABLE FINANCE.DOCUMENT ADD ORDER_INFOS CLOB;
ALTER TABLE FINANCE.DOCUMENT ADD SHOPPING_CARD_ID  VARCHAR2(50);

COMMENT ON COLUMN FINANCE.DOCUMENT.ORDER_INFOS IS 'ATTRS , RELATEDENTITIES et RELATEDPARTIES d order';
COMMENT ON COLUMN FINANCE.DOCUMENT.SHOPPING_CARD_ID IS 'Identifiant de shopping carte';

