ALTER TABLE FINANCE.DOCUMENT ADD (DEALER_ID_TMP NUMBER(38));
UPDATE FINANCE.DOCUMENT SET DEALER_ID_TMP = TO_NUMBER(DEALER_ID);
ALTER TABLE FINANCE.DOCUMENT DROP COLUMN DEALER_ID;
ALTER TABLE FINANCE.DOCUMENT RENAME COLUMN DEALER_ID_TMP TO DEALER_ID;