BEGIN

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('6','3421280011','Compte Clients Officiels', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('7','3421180022','Offices et Etablissements Publics', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('8','3421180021','Compte Collectivités Locales', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('25','3421180011','Compte Client Particulier', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('26','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('27','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('28','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('29','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('30','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('31','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('32','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('33','3421180012','Compte Revendeurs agréés', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('35','3421180011','Compte Client Particulier', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('36','3421180025','Grossiste Linéatec', SYSDATE, 'RET' );

INSERT INTO FINANCE.ACCOUNT_RECEIVABLE  (CATEGORY_ID ,AR_GLCODE, GLADESC,  ENTRY_DATE,  CATALOG )
                    values ('37','3421180028','Annonceurs Annuaires', SYSDATE, 'RET' );

COMMIT;

END;
/