CREATE SEQUENCE FINANCE.DOCUMENT_DETAIL_SEQ_ID_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  CACHE 20
  NOORDER
  NOCYCLE;

CREATE OR REPLACE PUBLIC SYNONYM DOCUMENT_DETAIL_SEQ_ID_SEQ FOR FINANCE.DOCUMENT_DETAIL_SEQ_ID_SEQ;

GRANT SELECT ON FINANCE.DOCUMENT_DETAIL_SEQ_ID_SEQ TO LIQUI_DML_ROLE;