ALTER TABLE FINANCE.PAYMENT ADD DEALER_NAME VARCHAR2(20);
ALTER TABLE FINANCE.PAYMENT ADD DEALER_ID VARCHAR2 (10);

COMMENT ON COLUMN FINANCE.PAYMENT.DEALER_NAME IS 'Nom de l agence';
COMMENT ON COLUMN FINANCE.PAYMENT.DEALER_ID IS 'Identifiant de l agence';
