CREATE TABLE FINANCE.BANK
(
		BANK_ID              NUMBER(38),
		BANK_CODE            VARCHAR2 (3) UNIQUE NOT NULL,
		BANK_NAME            VARCHAR2 (40)  NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.BANK.BANK_ID               IS 'ID interne de la table';
COMMENT ON COLUMN FINANCE.BANK.BANK_CODE             IS 'Code banque';
COMMENT ON COLUMN FINANCE.BANK.BANK_NAME             IS 'Nom de la banque';

ALTER TABLE FINANCE.BANK ADD CONSTRAINT PK_BANK_ID PRIMARY KEY  (BANK_ID);

CREATE OR REPLACE PUBLIC SYNONYM BANK FOR FINANCE.BANK;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.BANK TO LIQUI_DML_ROLE;