BEGIN

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (1, '023', 'ABN.AMRO Bank');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (2, '002', 'Arab Bank Maroc');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (3, '007', 'Attijariwafa bank');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (4, '190', 'Banque Centrale Pop.');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (5, '025', 'Banque Mar.Afr.Orien');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (6, '011', 'Bq.Mar.du Com.Exter.');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (7, '013', 'Bq.Mar.Pr.Com.Indus.');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (8, '230', 'Credit Immo.Hotelier');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (9, '021', 'Credit du Maroc');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (10, '225', 'Caisse Nle Cred.Agri');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (11, '022', 'Ste.Gle.Mne.Banques');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (12, '031', 'Ste.Mne.Depot Credit');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (13, '026', 'Union Banc.Hisp.Marr');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (14, '005', 'Union Mne.de Banques');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (15, '019', 'Wafabank');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (16, '205', 'Bq.Nle.Develop.Econo');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (17, '028', 'Citibank Maghreb');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (18, '999', 'Ste Banque et Credit');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (19, '001', 'Bank Al-Maghrib');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (20, '350', 'Centre Ch�ques Post.');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (21, '310', 'Tresorerie Generale');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (22, '032', 'Banco Bilbao Argenta');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (23, '051', 'Caisse Depot Gestion');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (24, '052', 'Paiements Vignettes');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (41, '101', 'B.P D''AGADIR');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (42, '105', 'B.P D''ALHOCEIMA');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (43, '109', 'B.P DE BENIMELLAL');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (44, '117', 'B.P D''EL JADIDA');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (45, '127', 'B.P DE FES');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (46, '133', 'B.P DU GHARB');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (47, '143', 'B.P DE LAAYOUNE');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (48, '145', 'B.P DE MARRAKECH');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (49, '148', 'B.P DE MEKNES');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (50, '150', 'B.P DE NADOR');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (51, '155', 'B.P DE OUARZAZATE');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (52, '157', 'B.P D''OUJDA');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (53, '159', 'B.P DE SAFI');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (54, '164', 'B.P DE TANGER');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (55, '169', 'B.P DE TAZA');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (56, '172', 'B.P DE TETOUAN');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (57, '175', 'B.P DE TIZNIT');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (58, '178', 'BPR CASABLANCA');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (59, '181', 'B.P DE RABAT');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (60, '140', 'B.P DE KHOURIBGA');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (61, '195', 'B.P DE CASA EST');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (62, '197', 'B.P de CASA SUD');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (63, '528', 'B.P DE TAFERSIT');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (71, '071', 'Liberty TEL');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (90, '090', 'Effet de Commerce');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (98, '098', 'Centre vignette');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (99, '099', 'Banque ONPT');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (100, '003', 'La Caixa Succursale');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (101, '070', 'BANCO SABADELL');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (102, '050', 'CFG Group');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (103, '362', 'Bank Assafa');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (104, '360', 'Umnia bank');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (105, '363', 'Dar-Al-Amane');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (106, '366', 'BANK AL YOUSR');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (107, '361', 'Najmah Bank');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (108, '367', 'BTI BANK');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (109, '365', 'Alakhdar Bank');

INSERT INTO FINANCE.BANK (BANK_ID, BANK_CODE, BANK_NAME)
     VALUES (110, '364', 'Arreda Bank');

COMMIT;

END;
/