CREATE TABLE FINANCE.PAYMENT_MODE
(
		PAY_MODE_ID 	NUMBER(38)      NOT NULL,
		PAY_MODE_CODE   VARCHAR2(10)    NOT NULL,
		PAY_MODE_DES	VARCHAR2(30)    NOT NULL,
		ENT_DATE	    DATE            DEFAULT SYSDATE,
		ISACTIVE	    VARCHAR2(1),
		PAY_MODE_CAT	VARCHAR2(10),
		PRINT_FLAG	    VARCHAR2(1),
		PAYMENTCODE	    VARCHAR2(1),
		ISEXTERNAL	    VARCHAR2(1)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_ID         IS 'ID interne du mode de paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_CODE       IS 'ID publique du mode de paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_DES        IS 'Description du mode de paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.ENT_DATE            IS 'Date de saisie';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.ISACTIVE            IS 'État du mode de paiement :
Y : Actif
N : Inactif';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAY_MODE_CAT        IS 'Catégorie du mode de paiement. CASH, CHEQ, CARD …etc.';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PRINT_FLAG          IS 'Flag d''impression du reçu de paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.PAYMENTCODE         IS 'Payment code in EB (PAYMENTTYPE_ALL.PAYMENTCODE)';
COMMENT ON COLUMN FINANCE.PAYMENT_MODE.ISEXTERNAL          IS 'Mode de paiement utilisé par un SI externe :
E : Uniquement par les SI externes,
mode non accessible à partir du Front
Payment.
B : Accessible à travers le front
Payment et les SI externes
NULL : Accessible uniquement à travers
le front Payment.';

ALTER TABLE FINANCE.PAYMENT_MODE ADD CONSTRAINT PK_PAY_MODE_ID PRIMARY KEY  (PAY_MODE_ID);

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_MODE FOR FINANCE.PAYMENT_MODE;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT_MODE TO LIQUI_DML_ROLE;