INSERT INTO FINANCE.TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC)
VALUES (7, 'AVOIR', 'Créer avoir');

INSERT INTO FINANCE.TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC)
VALUES (8, 'CASH-IN', 'MT Cash cash-in');

INSERT INTO FINANCE.TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC)
VALUES (9, 'CASH-OUT', 'MT Cash cash-out');

INSERT INTO FINANCE.TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC)
VALUES (10, 'CREDIT', 'MT Cash crédit');

INSERT INTO FINANCE.TRANSACTION_TYPE (TRX_ID, TRX_CODE, TRX_DESC)
VALUES (11, 'DEBIT', 'MT Cash débit');