ALTER TABLE FINANCE.PAYMENT ADD (DEALER_ID_TMP NUMBER(38));
UPDATE FINANCE.PAYMENT SET DEALER_ID_TMP = TO_NUMBER(DEALER_ID);
ALTER TABLE FINANCE.PAYMENT DROP COLUMN DEALER_ID;
ALTER TABLE FINANCE.PAYMENT RENAME COLUMN DEALER_ID_TMP TO DEALER_ID;