ALTER TABLE FINANCE.DISPATCH MODIFY PAY_MODE_ID NUMBER(38);

ALTER TABLE FINANCE.DISPATCH
    ADD (
        CONSTRAINT FK_DISPATCH_PAYMENT_MODE FOREIGN KEY
            (PAY_MODE_ID)
            REFERENCES FINANCE.PAYMENT_MODE (PAY_MODE_ID)
                ENABLE VALIDATE);