BEGIN

INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (1, 'R', 'Chèque sans provision', 'SANSPROV');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (2, 'R', 'Chèque avec provision insuffisante', 'PROVISUFF');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (3, 'R', 'Chèque mal libellé', 'BADLABEL');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (4, 'R', 'Chèque non signé', 'MISSINGSIGN');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (5, 'R', 'Chèque somme non conforme', 'AMTNCONFO');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (6, 'R', 'Chèque endossable irrégulier', 'ENDIRREG');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (7, 'R', 'Client décédé', 'CLTDECED');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (8, 'R', 'Compte saisie arrêt', 'CMPTSAISI');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (9, 'R', 'Compte clôturé', 'CMPTCLOT');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (10, 'R', 'Compte soldé', 'CMPTSOLD');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (11, 'R', 'Prélèvement non autorisé', 'NONAUTH');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (12, 'R', 'Erreur de saisie', 'ERRSAISIE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (13, 'R', 'Signature non conforme', 'SIGNNCONF');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (14, 'R', 'Non indication de la somme à payer', 'MISSINGAMT');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (15, 'R', 'Absence dénomination du chèque', 'MISSINGNAME');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (16, 'R', 'Signature non conforme', 'SIGNNCONF');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (17, 'R', 'Image chèque illisible', 'CHKILLISIBLE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (18, 'R', 'Surcharge et rature', 'SURCHRATURE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (19, 'R', 'Opposition au paiement', 'OPPOSITION');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (20, 'R', 'Chèque Prescrit', 'CHKPRESCRIT');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (21, 'R', 'Absence date et lieu d''émission', 'MISSINGDTPLCE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (22, 'R', 'Manque 2éme signature', 'MISSING2SIGN');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (23, 'A', 'Erreur de saisie sur client', 'CLTERROR');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (24, 'A', 'Erreur de saisie sur mode de paiement', 'MODEERROR');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (25, 'A', 'Erreur de saisie sur montant', 'AMTERROR');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (26, 'A', 'Erreur de saisie sur facture', 'INVERROR');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (27, 'A', 'Désistement client', 'DEMANDE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (28, 'A', 'Chèque mal libéllé', 'BADLABEL');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (29, 'A', 'Chèque non signé', 'MISSINGSIGN');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (30, 'A', 'Somme non-conforme', 'AMTNCONFO');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (31, 'A', 'Surcharge et rature', 'SURCHRATURE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (32, 'A', 'Client Black liste', 'BLACKLIST');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (33, 'A', 'Effet mal libellé', 'EFFBADLABEL');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (34, 'A', 'Bon vignette mal libellé', 'VIGNBADLABEL');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (35, 'A', 'Bon vignette échus', 'VIGNEXPIRED');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (36, 'A', 'Inexistence de la contre partie bancaire', 'MISSINGCOUNTER');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (37, 'A', 'Double prise en charge', 'DOUBLE');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (38, 'A', 'Annul mass, suite paiement non abouti CMI', 'MASSCANCLCMI');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (39, 'A', 'Annul mass, suite paiement non abouti M2T', 'MASSCANCLM2T');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (40, 'A', 'Annul garantie mise à disposition', 'CANCLDEPOSIT');
INSERT INTO FINANCE.REASON (REASON_ID, REASON_STATUS, REASON_DES, CODE) VALUES (41, 'A', 'Paiement annulé depuis canal digital', 'ANN_DIG');

COMMIT;

END;
/