CREATE OR REPLACE TRIGGER FINANCE.TRG_DOCUMENT_REF_NUM
BEFORE INSERT ON FINANCE.DOCUMENT
FOR EACH ROW
BEGIN
	IF :NEW.CATALOG = 'RET' THEN
	  IF :NEW.REF_NUM IS NULL THEN
	    :NEW.REF_NUM := 'RET' || LPAD(REF_NUM_SEQ.NEXTVAL, 15, '0');
	  END IF;
	END IF;
END;
/