CREATE TABLE FINANCE.ACCOUNT_RECEIVABLE
(
		CATEGORY_ID    VARCHAR2 (10),
		AR_GLCODE      VARCHAR2 (30),
		CATEGORY_DESC  VARCHAR2 (30),
		GLADESC        VARCHAR2 (60),
		ENTRY_DATE     DATE,
		CATALOG        VARCHAR2 (10)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.ACCOUNT_RECEIVABLE.CATEGORY_ID    IS 'Code de la catégorie (PRGCODE)';
COMMENT ON COLUMN FINANCE.ACCOUNT_RECEIVABLE.AR_GLCODE      IS 'Code comptable';
COMMENT ON COLUMN FINANCE.ACCOUNT_RECEIVABLE.CATEGORY_DESC  IS 'Description de la catégorie';
COMMENT ON COLUMN FINANCE.ACCOUNT_RECEIVABLE.GLADESC        IS 'Description du code comptable';
COMMENT ON COLUMN FINANCE.ACCOUNT_RECEIVABLE.ENTRY_DATE     IS 'Date de saisie';
COMMENT ON COLUMN FINANCE.ACCOUNT_RECEIVABLE.CATALOG        IS 'Code du catalogue :
RET dans le cas de vente RETAIL
TEL : pour le catalogue TELCO';

ALTER TABLE FINANCE.ACCOUNT_RECEIVABLE ADD CONSTRAINT PK_ACCOUNT_RECEIVABLE PRIMARY KEY  (CATEGORY_ID, AR_GLCODE);

CREATE OR REPLACE PUBLIC SYNONYM ACCOUNT_RECEIVABLE FOR FINANCE.ACCOUNT_RECEIVABLE;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.ACCOUNT_RECEIVABLE TO LIQUI_DML_ROLE;