CREATE TABLE FINANCE.PAYMENT_STATUS
(
		PAYMENT_ID	NUMBER(38),
		SEQNO     	NUMBER(38),
		STATUS	    VARCHAR2(1),
		STATUS_DATE DATE,
		USER_ID	    VARCHAR2 (10),
		REASON_ID	NUMBER(38)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.PAYMENT_ID    IS 'ID interne du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.SEQNO         IS 'Séquence Oracle de l’ID du statut du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.STATUS        IS 'État du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.STATUS_DATE   IS 'Date du statut';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.USER_ID       IS 'User ayant modifié le statut du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_STATUS.REASON_ID     IS 'Raison de rejet du paiement';

ALTER TABLE FINANCE.PAYMENT_STATUS ADD CONSTRAINT PK_PAYMENT_STATUS_ID PRIMARY KEY  (SEQNO);

ALTER TABLE FINANCE.PAYMENT_STATUS
    ADD (
        CONSTRAINT FK_PAYMENT_STATUS_PAYMENT_ID FOREIGN KEY
            (PAYMENT_ID)
            REFERENCES FINANCE.PAYMENT (PAYMENT_ID)
            ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_STATUS FOR FINANCE.PAYMENT_STATUS;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT_STATUS TO LIQUI_DML_ROLE;