CREATE USER FINANCE IDENTIFIED BY FINANCE DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO FINANCE;
GRANT RESOURCE TO FINANCE;

ALTER USER FINANCE QUOTA UNLIMITED ON DATA;
ALTER USER FINANCE QUOTA UNLIMITED ON INDX;





