CREATE TABLE FINANCE.PAYMENT_DETAIL
(
		PAYMENT_ID	NUMBER(38),
		DOCUMENT_ID	NUMBER(38),
		PAID_AMOUNT	FLOAT(126)      NOT NULL,
		GLCODE	    VARCHAR2 (10)   NOT NULL,
		SYSTEM	    VARCHAR2 (10),
		EXTERNAL_ID FLOAT(126)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.PAYMENT_ID     IS 'ID interne du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.DOCUMENT_ID    IS 'ID du document objet du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.PAID_AMOUNT    IS 'Montant payé par document';
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.GLCODE         IS 'Code comptable';
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.SYSTEM         IS 'Système ayant issu le document objet du paiement :
                                                            • RETAIL (Prépayé)
                                                            • TELCO (Postpayé)
                                                            • WIAM (Fixe/Internet)';
COMMENT ON COLUMN FINANCE.PAYMENT_DETAIL.EXTERNAL_ID    IS 'ID du paiement sur le SI externe (EB/WIAM)';

ALTER TABLE FINANCE.PAYMENT_DETAIL ADD CONSTRAINT PK_PAYMENT_DETAIL_ID PRIMARY KEY  (PAYMENT_ID, DOCUMENT_ID);

ALTER TABLE FINANCE.PAYMENT_DETAIL
    ADD (
        CONSTRAINT FK_PAYMENT_DETAIL_PAYMENT_ID FOREIGN KEY
            (PAYMENT_ID)
            REFERENCES FINANCE.PAYMENT (PAYMENT_ID)
            ENABLE VALIDATE);

ALTER TABLE FINANCE.PAYMENT_DETAIL
    ADD (
        CONSTRAINT FK_PAYMENT_DETAIL_DOCUMENT_ID FOREIGN KEY
            (DOCUMENT_ID)
            REFERENCES FINANCE.DOCUMENT (DOCUMENT_ID)
            ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT_DETAIL FOR FINANCE.PAYMENT_DETAIL;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT_DETAIL TO LIQUI_DML_ROLE;