CREATE TABLE FINANCE.DISPATCH
(
		DISPATCH_ID     NUMBER(38) NOT NULL,
		ENTRY_DATE      DATE            DEFAULT SYSDATE,
		CREATED_BY      VARCHAR2(30)    NOT NULL,
		PAY_MODE_ID     NUMBER(38)      NOT NULL,
		AMOUNT          FLOAT(126)      NOT NULL,
		COST_ID         NUMBER(38)      NOT NULL,
		BAG_NUMBER      VARCHAR2(50),
		REMITTANCE_ID   VARCHAR2(50),
		REMITTANCE_DATE DATE,
		REMITTED_BY     VARCHAR2(30)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.DISPATCH.DISPATCH_ID      IS 'ID interne de la table. Séquence Oracle.';
COMMENT ON COLUMN FINANCE.DISPATCH.ENTRY_DATE       IS 'Date de génération du numéro de bordereau.';
COMMENT ON COLUMN FINANCE.DISPATCH.CREATED_BY       IS 'Login du régisseur ayant édité le bordereau.';
COMMENT ON COLUMN FINANCE.DISPATCH.PAY_MODE_ID      IS 'ID du mode de paiement.';
COMMENT ON COLUMN FINANCE.DISPATCH.AMOUNT           IS 'Montant total du bordereau.';
COMMENT ON COLUMN FINANCE.DISPATCH.COST_ID          IS 'ID du centre de coût de l’agence.';
COMMENT ON COLUMN FINANCE.DISPATCH.BAG_NUMBER       IS 'Numéro du sac de remise.';
COMMENT ON COLUMN FINANCE.DISPATCH.REMITTANCE_ID    IS 'Numéro de la remise.';
COMMENT ON COLUMN FINANCE.DISPATCH.REMITTANCE_DATE  IS 'Date de la remise.';
COMMENT ON COLUMN FINANCE.DISPATCH.REMITTED_BY      IS 'Login du régisseur ayant remis les fonds aux convoyeurs.';

ALTER TABLE FINANCE.DISPATCH ADD CONSTRAINT PK_DISPATCH_ID PRIMARY KEY (DISPATCH_ID);

CREATE OR REPLACE PUBLIC SYNONYM DISPATCH FOR FINANCE.DISPATCH;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.DISPATCH TO LIQUI_DML_ROLE;