CREATE TABLE FINANCE.BANK_BRANCH
(
		BRANCH_ID            NUMBER(38),
		BANK_ID              NUMBER(38),
		BRANCH_CODE          VARCHAR2 (3)  NOT NULL,
		BRANCH_NAME          VARCHAR2 (40) NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.BANK_BRANCH.BRANCH_ID               IS 'ID interne de la table';
COMMENT ON COLUMN FINANCE.BANK_BRANCH.BANK_ID                 IS 'ID de la banque mère';
COMMENT ON COLUMN FINANCE.BANK_BRANCH.BRANCH_CODE             IS 'Code agence bancaire';
COMMENT ON COLUMN FINANCE.BANK_BRANCH.BRANCH_NAME             IS 'Nom de l''agence bancaire';

ALTER TABLE FINANCE.BANK_BRANCH ADD CONSTRAINT PK_BRANCH_ID PRIMARY KEY  (BRANCH_ID);

CREATE OR REPLACE PUBLIC SYNONYM BANK_BRANCH FOR FINANCE.BANK_BRANCH;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.BANK_BRANCH TO LIQUI_DML_ROLE;