ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD PRODUCT_DESC VARCHAR2 (100);
ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD SAP_CODE VARCHAR2 (20);
ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD IS_BUNDLED NUMBER(1,0) DEFAULT 0 NOT NULL CHECK (IS_BUNDLED IN (0, 1));
ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD ITEM_ID VARCHAR2(60);
ALTER TABLE FINANCE.DOCUMENT_DETAIL ADD PARENT_ITEM_ID VARCHAR2(60);


COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.PRODUCT_DESC IS 'Description du produit';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.SAP_CODE IS 'Code SAP du produit';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.IS_BUNDLED IS 'Flag indiquant si le produit est composé de sous-produits (Pack)';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.ITEM_ID IS 'Identifiant de l item';
COMMENT ON COLUMN FINANCE.DOCUMENT_DETAIL.PARENT_ITEM_ID IS 'Identifiant de l item parent (Cas d un produit faisant parti d un pack)';