CREATE TABLE FINANCE.PAYMENT
(
		PAYMENT_ID	  NUMBER(38) NOT NULL,
		CUSTOMERID	  VARCHAR2(40) NOT NULL,
		CUSTNUM	      VARCHAR2 (30) NOT NULL,
		ENT_DATE	  DATE          DEFAULT SYSDATE,
		CHK_DATE	  DATE,
		CHK_NUM       VARCHAR2 (30) NOT NULL,
		PAY_MODE_ID	  NUMBER(38)    NOT NULL,
		AMOUNT	      FLOAT(126)    NOT NULL,
		STATUS	      VARCHAR2(1)   NOT NULL,
		USER_ID	      VARCHAR2(10)  NOT NULL,
		COMMENTS      VARCHAR2(30),
		POST_GL_DATE  DATE,
		POST_PERIOD   VARCHAR2 (6)  NOT NULL,
		COST_ID	      NUMBER(38)    NOT NULL,
		GLENTRY_ID    NUMBER(38),
		PAY_GLCODE	  VARCHAR2 (30),
		STAMP_AMT	  FLOAT(126),
		BORDU_NUM	  VARCHAR2 (30),
		BANK_CODE	  VARCHAR2 (3),
		BRANCH_CODE	  VARCHAR2 (5),
		BANK_ACCNO	  VARCHAR2 (24),
		BANK_NAME	  VARCHAR2 (30),
		RIB_KEY	      VARCHAR2 (2),
		SOURCE	      VARCHAR2 (10),
		EBSYNCHED	  VARCHAR2 (1)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.PAYMENT.PAYMENT_ID       IS 'ID interne du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT.CUSTOMERID      IS 'Customer ID au niveau du CPR';
COMMENT ON COLUMN FINANCE.PAYMENT.CUSTNUM          IS 'ID publique du client';
COMMENT ON COLUMN FINANCE.PAYMENT.ENT_DATE         IS 'Date de saisie du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT.CHK_DATE         IS 'Date de référence du paiement : Date du chèque par ex.';
COMMENT ON COLUMN FINANCE.PAYMENT.CHK_NUM          IS 'Numéro de référence : N° du chèques, Référence de virement, transaction TPE etc.';
COMMENT ON COLUMN FINANCE.PAYMENT.PAY_MODE_ID      IS 'Id du mode de paiement';
COMMENT ON COLUMN FINANCE.PAYMENT.AMOUNT           IS 'Montant du paiement';
COMMENT ON COLUMN FINANCE.PAYMENT.STATUS           IS 'Statut du paiement :
E : Encaissé
S : Soumis
V : Validé
D : Déposé
A : Annulé
R : Rejeté';
COMMENT ON COLUMN FINANCE.PAYMENT.USER_ID          IS 'Login de l’agent';
COMMENT ON COLUMN FINANCE.PAYMENT.COMMENTS         IS 'Commentaire';
COMMENT ON COLUMN FINANCE.PAYMENT.POST_GL_DATE     IS 'Date de transfert de la transaction au Grand Livre';
COMMENT ON COLUMN FINANCE.PAYMENT.POST_PERIOD      IS 'Période comptable';
COMMENT ON COLUMN FINANCE.PAYMENT.COST_ID          IS 'ID du centre de coût';
COMMENT ON COLUMN FINANCE.PAYMENT.GLENTRY_ID       IS 'Id de la transaction de transfert vers GL';
COMMENT ON COLUMN FINANCE.PAYMENT.PAY_GLCODE       IS 'Code comptable de l’encaissement';
COMMENT ON COLUMN FINANCE.PAYMENT.STAMP_AMT        IS 'Montant des droits de timbre dans le cas de paiement en Espèces';
COMMENT ON COLUMN FINANCE.PAYMENT.BORDU_NUM        IS 'Référence du bordereau de remise';
COMMENT ON COLUMN FINANCE.PAYMENT.BANK_CODE        IS 'Code de banque si applicable';
COMMENT ON COLUMN FINANCE.PAYMENT.BRANCH_CODE      IS 'Code de l’agence bancaire';
COMMENT ON COLUMN FINANCE.PAYMENT.BANK_ACCNO       IS 'Numéro du compte bancaire';
COMMENT ON COLUMN FINANCE.PAYMENT.BANK_NAME        IS 'Intitulé de la banque';
COMMENT ON COLUMN FINANCE.PAYMENT.RIB_KEY          IS 'Clé RIB';
COMMENT ON COLUMN FINANCE.PAYMENT.SOURCE           IS 'Payment source:
PG – Payment Gateway
EB – Ericsson Billing';
COMMENT ON COLUMN FINANCE.PAYMENT.EBSYNCHED        IS 'Flag de synchronisation du paiement avec EB';

ALTER TABLE FINANCE.PAYMENT ADD CONSTRAINT PK_PAYMENT_ID PRIMARY KEY  (PAYMENT_ID);

ALTER TABLE FINANCE.PAYMENT
    ADD (
        CONSTRAINT FK_PAYMENT_PAY_MODE_ID FOREIGN KEY
            (PAY_MODE_ID)
            REFERENCES FINANCE.PAYMENT_MODE (PAY_MODE_ID)
            ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM PAYMENT FOR FINANCE.PAYMENT;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.PAYMENT TO LIQUI_DML_ROLE;