CREATE TABLE FINANCE.REASON
(
		REASON_ID	    NUMBER(38),
		REASON_STATUS	VARCHAR2 (1),
		REASON_DES	    VARCHAR2 (50),
		CODE            VARCHAR2 (15)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN FINANCE.REASON.REASON_ID        IS 'ID interne de la raison';
COMMENT ON COLUMN FINANCE.REASON.REASON_STATUS    IS 'Status de la raison';
COMMENT ON COLUMN FINANCE.REASON.REASON_DES       IS 'Description de la raison';
COMMENT ON COLUMN FINANCE.REASON.CODE             IS 'Code de la raison';

ALTER TABLE FINANCE.REASON ADD CONSTRAINT PK_REASON_ID PRIMARY KEY  (REASON_ID);

CREATE OR REPLACE PUBLIC SYNONYM REASON FOR FINANCE.REASON;

GRANT SELECT, UPDATE, DELETE, INSERT ON FINANCE.REASON TO LIQUI_DML_ROLE;