---------------------------------Headline------------------------------
-- System/Module : 			BSCS EB
-- Script Name   : 			DML_INIT_CONTROL_ENTITY.sql
-- Created by    :     	Adnane AMELLAL
-- Creation date : 			11/06/2025
--    
-- Modified by        
-- Modification date    
-- Modification Reason 
--        
-- Version          1.0                
-- DELIVERY 	    	
-- Tables impacted  
--
-- Description:
--
-- Parameters     IN/OUT
--------------------------------Barcode--------------------------------
SET ARRAYSIZE 1;
SET ECHO ON;
SET SERVEROUTPUT ON;
EXECUTE DBMS_OUTPUT.ENABLE(1000000);
WHENEVER SQLERROR EXIT 1 ROLLBACK;
WHENEVER OSERROR  EXIT 2 ROLLBACK;
UNDEF V_SYSDATE
SET FEEDBACK ON;

COLUMN V_SYSDATE  NEW_VALUE V_SYSDATE   NOPRINT
SELECT TO_CHAR (SYSDATE, 'yyyymmddhh24miss') V_SYSDATE FROM DUAL;

SPOOL $WORK/TMP/DML_INIT_CONTROL_ENTITY.&&V_SYSDATE..LST


BEGIN

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (1, 'RABAT AGDAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (2, 'RABAT AKKARI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (3, 'RABAT AMBASSADEURS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (4, 'RABAT CENTRE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (5, 'RABAT DIOUR JEMAA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (6, 'RABAT ENTREPRISES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (7, 'RABAT HASSAN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (8, 'RABAT NAHDA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (9, 'RABAT MASSIRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (10, 'RABAT TAKADDOUM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (11, 'RABAT ROUMMANI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (12, 'RABAT RIAD');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (13, 'CENTRE DE PROFIL IAM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (14, 'OFFICIELS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (15, 'AGENCES BANQUES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (16, 'AIN CHOK HADDAOUIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (17, 'AIN HARROUDA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (18, 'AIN SEBAA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (19, 'AIT MELLOUL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (20, 'AIT OURIR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (21, 'AIT SOUSS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (22, 'AL BOUKHARI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (23, 'AL HOUCEIMA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (24, 'AMZMIZ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (25, 'ASSILAH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (26, 'AZILAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (27, 'AZROU');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (28, 'BANDOENG');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (29, 'BD DE PARIS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (30, 'BEJAAD');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (31, 'BEL VÉDERE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (32, 'BEN AHMED');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (33, 'BEN SLIMANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (34, 'BENGRIR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (35, 'BENI MELLAL EL KHATTABI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (36, 'BENSOUDA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (37, 'BERKANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (38, 'BERNOUSSI ESSAADA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (39, 'BERRCHID');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (40, 'BIOUGRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (41, 'BOUARFA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (42, 'BOUCHENTOUF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (43, 'SIDI OTHMANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (44, 'CENTRE GSM TEMARA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (45, 'CHEFCHAOUEN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (46, 'CHICHAOUA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (47, 'CITY PARK');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (48, 'DAHKLA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (49, 'FES ADARISSA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (50, 'DRISSIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (51, 'EL AIOUN OUJDA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (52, 'EL BROUJ SETTAT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (53, 'EL FIDACENTRAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (54, 'EL HAJEB');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (55, 'EL JADIDA NAKHIL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (56, 'EL KELAÂ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (57, 'EL OUELFA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (58, 'ENNAJD');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (59, 'ENTRAIDE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (60, 'ENTREPRISES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (61, 'ENTREPRISES I');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (62, 'ENTREPRISES II');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (63, 'ENTREPRISES NU');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (64, 'ERFOUD');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (65, 'ERRACHIDIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (66, 'ESPACE SAISS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (67, 'ESSAOUIRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (68, 'ESSEMARA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (69, 'FÈS ATLAS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (70, 'FÈS BATHA MÉDINA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (71, 'FES JDID DAR DBIBEGH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (72, 'FÈS RCIF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (73, 'FIGUIG');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (74, 'FKIH BEN SALEH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (75, 'GOULMIM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (76, 'GUERCIF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (77, 'HASSAN 1ER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (78, 'SALÉ HAY ESSALAM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (79, 'HAY HASSANI EL OULFA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (80, 'HAY MOHAMMADI GARE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (81, 'IBN ROCHD');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (83, 'IFRANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (84, 'IMINTANOUT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (85, 'INBIAT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (86, 'INEZGANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (87, 'JERADA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (88, 'K. DES SRAGHNA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (89, 'KASBA TADLA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (90, 'KÉNITRA CENTRE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (91, 'KÉNITRA SAKNIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (92, 'KÉNITRA VILLE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (93, 'KHEMISSET CENTRE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (94, 'KHEMISSET HAY ESSALAM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (95, 'KHENIFRA MED V');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (96, 'KHOURIBGA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (97, 'KSAR EL KÉBIR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (98, 'LAAYOUNE VILLE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (99, 'LARACHE AL WAFAE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (100, 'LARACHE VILLE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (101, 'LES AMICALE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (102, 'M. ENTREPRISES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (103, 'M. MHAMID');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (104, 'M.MASSIRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (105, 'M.VI ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (106, 'MAARIF (EL FOURAT)');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (107, 'MARJANE BOUSKOURA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (108, 'MARRAK MOBILE MARJANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (109, 'MARRAKECH ASSIF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (110, 'MARRAKECH MÉDINA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (111, 'MARRAKECH MOBILE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (112, 'MEKNÈS EL MENZEH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (113, 'MEKNÈS ISMAILIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (114, 'MERS SULTAN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (115, 'MIDELT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (116, 'MISSOUR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (117, 'MOHAMMADIA ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (118, 'MOHAMMADIA EL ALIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (119, 'MRIRT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (120, 'MY ISMAIL (SIJLMASSA)');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (121, 'MY RACHID');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (122, 'MY YOUSSEF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (123, 'NADOR CENTRE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (124, 'MARJANE FES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (125, 'SETTAT MOBILE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (126, 'OUARZAZATE MY RACHID');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (127, 'OUAZANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (128, 'OUARZAZATE TINGHIR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (129, 'OUED ZEM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (130, 'OUELED MIMOUN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (131, 'OUJDA HAY HASSANI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (132, 'OUJDA LAZARET');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (133, 'OUJDA MOBILE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (134, 'OUJDA MOHAMED V ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (135, 'OUJDA OUED NACHEF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (136, 'OULAD OUJIH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (137, 'OUSSAM BNOU ZAID');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (139, 'PAIEMENT NADOR MOBILE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (140, 'SETTAT ENTREPRISES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (142, 'RICH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (143, 'SAFI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (144, 'SAFI YOUSSOUFIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (145, 'SALE MEDINA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (146, 'SALE TABRIQUET');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (147, 'SALE VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (148, 'SEBATA OUED DAHAB');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (149, 'SEFROU');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (150, 'IBN BATTOUTA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (151, 'SETTAT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (152, 'SETTAT VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (153, 'SIDI BENNOUR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (154, 'SIDI EL MOKHTAR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (155, 'SIDI KACEM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (156, 'SIDI SLIMANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (157, 'SOUK EL ARBAA DU GHARB');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (158, 'SOUK SEBT BENI MELLAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (159, 'MARRAKECH SYBA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (160, 'TAHANAOUTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (161, 'TAN TAN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (162, 'TANGER BRANES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (163, 'TANGER DRADEB');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (164, 'TANGER DRISSIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (165, 'TANGER IBN TAYMIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (166, 'TANGER MY ISMAIL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (167, 'TANGER PASTEUR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (168, 'TANGER VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (169, 'TAOUNATE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (170, 'TAOURIRT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (171, 'TAROUDANT AKNIS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (172, 'TAZA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (173, 'TEMARA CENTRE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (174, 'TEMARA MASSIRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (175, 'TETOUAN AL AZHAR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (176, 'TETOUAN EL ADALA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (177, 'TETOUANE MY HASSAN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (178, 'TIFLET');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (179, 'TIZNIT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (180, 'TWIN CENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (181, 'VENTE INDIRECTE GUÉLIZ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (182, 'ZAGOURA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (183, 'CASA ZERKTOUNI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (184, 'FÈS ZMY');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (185, 'AGADIR ZERKTOUNI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (186, 'BOUJDOUR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (187, 'CASA HASSAN II');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (188, 'SCE RECOUVREMENT RABAT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (189, 'MAARIF IBNOU HAZEM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (190, 'REGIE DES SERVICES CENTRAUX');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (191, 'SETTAT MOHAMED V');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (192, 'OULED TEIMA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (193, 'SCE RECOUVREMENT OGP SALE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (194, 'OUJDA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (195, 'TATA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (196, 'CENTRE D''ENCAISSEMENT MOBILE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (197, 'MEKNES VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (198, 'CASA MOUAD BNOU JABAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (199, 'SALE KARIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (200, 'MARRAKECH ENTREPRISE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (201, 'GOULMIM 2');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (202, 'GOULMIM 3');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (203, 'TETOUAN VENTES INDIRECTES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (204, 'TIZNIT 2');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (205, 'TIZNIT 3');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (206, 'PAIEMENT VIGNETTES GC');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (207, 'PAIEMENT ALIA MOHAMMADIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (208, 'REGIE DES TABACS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (209, 'WAFA CASH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (210, 'AHFIR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (211, 'DRIOUCH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (212, 'PAIEMENT KOUTOUBIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (213, 'TARGUIST');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (214, 'KENITRA GARE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (215, 'MECHRAA BELKSIRI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (216, 'RABAT AL KIFAH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (217, 'CASA SIDI MAAROUF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (218, 'FNIDEQ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (219, 'OUJDA AL QODS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (220, 'M2T');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (221, 'OUJDA CENTRE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (222, 'EL JADIDA NABEUL MIXTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (223, 'MARINA AGADIR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (224, 'TAHLA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (225, 'BENI MAKADA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (226, 'ARSAT MY ABDESSALAM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (227, 'PEL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (228, 'HAY MOHAMMADI VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (229, 'HAD SOUALEM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (230, 'AIN CHOCK VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (231, 'HAY HASSANI VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (232, 'NASSIM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (233, 'SIDI OTHMANE VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (234, 'HARHOURA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (235, 'MEKNES DKHISSA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (236, 'EL FIDA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (237, 'EL FIDA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (238, 'AGENCE HAJ FATEH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (239, 'MARJANE HAY HASSANI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (240, 'ZEGHANGHANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (241, 'BNI NSAR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (242, 'BASSATINE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (243, 'CASA TIT MELLIL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (244, 'CASA MY RACHID PAIEMENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (245, 'AZEMMOUR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (246, 'CASA NU VENTE IND');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (247, 'MBC');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (248, 'CASA ENTREPRISE EL OULFA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (249, 'MEKNES ZERHOUNIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (250, 'AIN TAOUJDATE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (251, 'MOHAMMEDIA GARE ONCF');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (252, 'AGADIR GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (253, 'MARRAKECH GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (254, 'SETTAT GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (255, 'TANGER GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (256, 'CASABLANCA GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (257, 'RABAT GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (258, 'OUJDA GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (259, 'FES GESTION CLIENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (260, 'MARTIL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (261, 'MARRAKECH GUELIZ VENTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (262, 'MARRAKECH GULIZ VENTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (263, 'MARRAKECH PAIEMENT GUELIZ');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (264, 'AGADIR HASSAN 1ER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (265, 'DEROUA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (266, 'BENI MELLAL VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (267, 'CASA ANNASSI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (268, 'CASA MORROCO MALL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (269, 'KHEMIS ZEMAMRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (270, 'CASA AL QODS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (271, 'TAZA ALAOUIYINE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (272, 'FES BENSOUDA VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (273, 'OUJDA ALLAL EL FASSI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (274, 'EL KARIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (275, 'CASA MEDIOUNA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (276, 'MOHAMMEDIA ASSWAK ASSALAM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (277, 'GAM');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (278, 'KENITRA BIR RAMI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (279, 'FES MONFLEURIT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (280, 'EBOUTIQUE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (281, 'FES MARJANE SAISS');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (282, 'CASABLANCA NIL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (283, 'CASABLANCA PLACE ANFA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (284, 'SALE CARREFOUR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (285, 'CASA SIDI MAAROUF VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (286, 'MEKNES MARJANE II');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (287, 'CASABLANCA GHANDI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (288, 'CASA AL MOUSTAKBAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (289, 'KENITRA OULAD OUJIH II');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (290, 'CASA PORT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (291, 'CASA SBATA PAIEMENT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (292, 'CASA MARJANE DERB SOLTAN');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (293, 'MARJANE SIDI SLIMANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (294, 'CASABLANCA KHANSAA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (295, 'FES MOHAMED VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (296, 'AGADIR TALBORJT');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (297, 'CASABLANCA RAHMA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (298, 'BCPNET COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (299, 'FES WAFAE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (300, 'OUED FES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (301, 'IMOUZZER KANDAR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (302, 'CASA SIDI MOUMEN ADARISSA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (303, 'CASA ATTACHAROUK');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (304, 'BORJ FES');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (305, 'MEKNES AV DES FAR');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (306, 'MEKNES MED VI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (307, 'TANGER ROUDANI');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (308, 'LARACHE MARJANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (309, 'LARACHE MAGHRIB EL JADID');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (310, 'TANGER CITY CENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (311, 'CASA LISSASFA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (312, 'CASA SALMIA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (313, 'CASABLANCA MARINA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (314, 'DCHEIRA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (315, 'BARIDNET COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (317, 'PRD');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (318, 'B2PIP COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (319, 'NETAWB COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (320, 'CASA MARJANE SIDI OTHMANE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (321, 'SIDI RAHAL CHATII');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (322, 'MEKNES MEDINA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (323, 'AL HOCEIMA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (324, 'CASA MARJANE BNOU TACHFINE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (325, 'CASABLANCA DAR BOUAZZA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (326, 'NETCFG  COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (327, 'BIM  COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (328, 'SCF  COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (329, 'CMI PHYSIQUE COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (330, 'CMI DIGITAL COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (331, 'GAM ESE CASA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (332, 'SICOTEL ESE CASA');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (333, '5115180313');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (334, 'CASABLANCA GARE LGV');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (335, 'RABAT AGDAL GARE LGV');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (336, 'KENITRA GARE LGV');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (337, 'SALA AL JADIDA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (338, 'RABAT AL MANAL VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (339, 'IFRANE VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (340, 'ERRACHIDIA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (341, 'KHENIFRA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (342, 'SOUK EL ARBAA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (343, 'MOHAMMEDIA VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (344, 'KHEMISSET VENTE INDIRECTE');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (345, 'WAFACASH PHYSIQUE COSTCENTER');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (346, 'PAYEREV');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (347, 'EBOUTIQUE CENTRAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (348, 'MTCASH');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (349, 'M2T DIGITAL');

INSERT INTO SALESHIERARCHY.CONTROL_ENTITY (ENTITY_ID, ENTITY_DESC)
     VALUES (350, 'TAOUNATE VI');

--
 COMMIT;
-- 
END;
/

SPOOL OFF
EXIT;