/*<TOAD_FILE_CHUNK>*/
CREATE OR REPLACE PROCEDURE DELETE_CUSTOMER_DATA(cs_id IN NUMBER)
AS
BEGIN
DELETE FROM BCH_CUST_BILLED_AMOUNT WHERE customer_id = cs_id;
  DELETE FROM BCH_CUST_HISTORY WHERE customer_id = cs_id;
  DELETE FROM BCH_QA_INTERFACE_BILLACC WHERE customer_id = cs_id;
  DELETE FROM BCH_QA_INTERFACE WHERE customer_id = cs_id;
  DELETE FROM BILLCYCLE_ASSIGNMENT_HISTORY WHERE customer_id = cs_id;

  DELETE FROM BILLING_ACCOUNT_VERSION
  WHERE BILLING_ACCOUNT_ID IN (
    SELECT BILLING_ACCOUNT_ID FROM BILLING_ACCOUNT WHERE customer_id = cs_id
  );
  
    DELETE FROM PAYMENT_ARRANGEMENT_BILLACC
  WHERE BILLING_ACCOUNT_ID IN (
    SELECT BILLING_ACCOUNT_ID FROM BILLING_ACCOUNT WHERE customer_id = cs_id
  );

  DELETE FROM BILLING_ACCOUNT WHERE customer_id = cs_id;
  DELETE FROM BILL_SCHEDULE_AGREEMENT WHERE customer_id = cs_id;
  DELETE FROM BLUIFTAB WHERE customer_id = cs_id;
  DELETE FROM BOP_STATISTICS WHERE customer_id = cs_id;
  DELETE FROM CASHRECEIPTS_ALL WHERE customer_id = cs_id;
  DELETE FROM CCONTACT_HIST WHERE customer_id = cs_id;
  DELETE FROM CCONTACT_ALL WHERE customer_id = cs_id;
  DELETE FROM COLLECTIONS_DATA_CHANGED_CTRL WHERE customer_id = cs_id;
  DELETE FROM COLL_DATA_CHANGED_CTRL_HIST WHERE customer_id = cs_id;
  DELETE FROM CONCURRENT_REQUEST WHERE customer_id = cs_id;
  DELETE FROM CONTRACT_ALL WHERE customer_id = cs_id;
  DELETE FROM CONTR_TURNOVER WHERE customer_id = cs_id;
  DELETE FROM CREDIT_CLASS_ASSIGNMENT WHERE customer_id = cs_id;
  DELETE FROM CREDIT_CLASS_STATISTIC WHERE customer_id = cs_id;
  DELETE FROM CREDIT_CLASS_STATISTIC_SIM WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_COLLECTION WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_FAMILY WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_HISTORY WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_ROLE WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_TAX_EXEMPTION WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_TURNOVER WHERE customer_id = cs_id;
  DELETE FROM CUST_BUSUNIT_HIST WHERE customer_id = cs_id;
  DELETE FROM CUST_MLG_ATTACH WHERE customer_id = cs_id;
  DELETE FROM CUST_MLG_ITEM WHERE customer_id = cs_id;
  DELETE FROM DCH_COLLECTIBLE_CTRL WHERE customer_id = cs_id;
  DELETE FROM DCH_CSC_EVENT_CTRL WHERE customer_id = cs_id;
  DELETE FROM DEALER_INFO WHERE customer_id = cs_id;
    
  DELETE FROM CONTR_SERVICES_CAP
  WHERE DN_ID IN (
    SELECT DN_ID FROM DIRECTORY_NUMBER WHERE dealer_id = cs_id
  );
  
  DELETE FROM DIRECTORY_NUMBER WHERE dealer_id = cs_id;
  DELETE FROM EQUIPMENT WHERE customer_id = cs_id;
  DELETE FROM EXTERNAL_DOCUMENT_DATA WHERE customer_id = cs_id;
  DELETE FROM FAF_ELEMENTS WHERE customer_id = cs_id;
  DELETE FROM FEES WHERE customer_id = cs_id;
  DELETE FROM FUH_PROCESS_CONTR WHERE customer_id = cs_id;
  DELETE FROM FUH_PROCESS_CUST WHERE customer_id = cs_id;
  DELETE FROM FUP_ACCOUNTS_UPDATE WHERE customer_id = cs_id;
  DELETE FROM IMB_CUSTOMER WHERE customer_id = cs_id;
  DELETE FROM INDIVIDUAL_TAXATION WHERE customer_id = cs_id;
  DELETE FROM INFO_CUST_TEXT WHERE customer_id = cs_id;
  DELETE FROM LBC_DATE_HIST WHERE customer_id = cs_id;
  DELETE FROM MASS_TM_CHANGE WHERE customer_id = cs_id;
  DELETE FROM MPUFFTAB WHERE customer_id = cs_id;
  DELETE FROM MPUSHTAB WHERE customer_id = cs_id;
  DELETE FROM ORDERHDR_ALL WHERE customer_id = cs_id;
  DELETE FROM ORDERHDR_ALL_RENTAL WHERE customer_id = cs_id;
  DELETE FROM ORDER_LIMIT WHERE customer_id = cs_id;

  DELETE FROM PAYMENT_ARRANGEMENT_CUSTOMER
  WHERE PAYMENT_ID IN (
    SELECT PAYMENT_ID FROM PAYMENT_ALL WHERE customer_id = cs_id
  );
  DELETE FROM PAYMENT_ARRANGEMENT_BILLACC
  WHERE PAYMENT_ID IN (
    SELECT PAYMENT_ID FROM PAYMENT_ALL WHERE customer_id = cs_id
  );
  
  DELETE FROM PAYMENT_ALL WHERE customer_id = cs_id;
  
  DELETE FROM CONTR_SERVICES_CAP
  WHERE SM_ID IN (
    SELECT SM_ID FROM STORAGE_MEDIUM WHERE dealer_id = cs_id
  );
  
  DELETE FROM CONTR_DEVICES
  WHERE PORT_ID IN (
    SELECT PORT_ID FROM PORT WHERE dealer_id = cs_id
  );
  
  DELETE FROM PORT
  WHERE SM_ID IN (
    SELECT SM_ID FROM STORAGE_MEDIUM WHERE dealer_id = cs_id
  );
  
  DELETE FROM CONTR_SERVICES_PORT
  WHERE PORT_ID IN (
    SELECT PORT_ID FROM PORT WHERE dealer_id = cs_id
  );
  
  DELETE FROM STORAGE_MEDIUM WHERE dealer_id = cs_id;
  
  DELETE FROM PORT WHERE dealer_id = cs_id;
  
  DELETE FROM PAYMENT_PLAN_BSCS WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_HISTORY WHERE customer_id_high = cs_id;
  DELETE FROM PAYMENT_SOURCE WHERE customer_id = cs_id;
  DELETE FROM PERS_INVOICE_LIMIT_HIST WHERE customer_id = cs_id;
  DELETE FROM PORTING_REQUEST WHERE customer_id = cs_id;
  DELETE FROM PORTING_REQUEST_HISTORY WHERE customer_id = cs_id;
  DELETE FROM PROFILE_SERVICE_ADV_PROMO WHERE customer_id = cs_id;
  DELETE FROM PROMO_ACTION_STORAGE WHERE customer_id = cs_id;
  DELETE FROM PROMO_APPL_REWARDS WHERE customer_id = cs_id;
  DELETE FROM PROMO_ASSIGN WHERE customer_id = cs_id;
  DELETE FROM PROMO_BONUS_POINTS WHERE customer_id = cs_id;
  DELETE FROM PROMO_PROC_BONUS_POINTS WHERE customer_id = cs_id;
  DELETE FROM PROMO_PROC_CONTEXT WHERE customer_id = cs_id;
  DELETE FROM PROMO_PROC_POSTING_ACTION WHERE customer_id = cs_id;
  DELETE FROM PROMO_QUAL_RESTRICT WHERE customer_id = cs_id;
  DELETE FROM QUOTE_CUSTOMER WHERE customer_id = cs_id;
  DELETE FROM RATEPLAN_HIST_OCC WHERE customer_id = cs_id;
  DELETE FROM RDR_PROCESS_CUST WHERE customer_id = cs_id;
  DELETE FROM REMARKS_ALL WHERE customer_id = cs_id;
  DELETE FROM REVENUE_HISTORY WHERE customer_id = cs_id;
  DELETE FROM RLH_CUST_RATED_AMOUNT WHERE customer_id = cs_id;
  DELETE FROM RLH_OPEN_AMOUNT_LIMIT WHERE customer_id = cs_id;
  DELETE FROM ROLES_DEALERS WHERE customer_id = cs_id;
  DELETE FROM RR_CUSTOMER_LNK WHERE customer_id = cs_id;
  DELETE FROM SCHEDULED_JOB WHERE customer_id = cs_id;
  DELETE FROM SCHEDULED_JOB_HISTORY WHERE customer_id = cs_id;
  DELETE FROM SERVICE_PROVIDER_SERVICES WHERE customer_id = cs_id;
  DELETE FROM SMALL_INVOICE_OMISSION WHERE customer_id = cs_id;
  DELETE FROM TICKLER_RECORDS WHERE customer_id = cs_id;
  DELETE FROM UNDO_DOC_REF_NUMS WHERE customer_id = cs_id;
  DELETE FROM UNDO_TRANSACTION_LOG WHERE customer_id = cs_id;
  DELETE FROM CUSTOMER_ALL WHERE CUSTOMER_ID = cs_id;
END;
/

/*<TOAD_FILE_CHUNK>*/
GRANT EXECUTE ON DELETE_CUSTOMER_DATA TO LIQUI_DML_ROLE;

CREATE PUBLIC SYNONYM DELETE_CUSTOMER_DATA FOR DELETE_CUSTOMER_DATA;

