CREATE TABLE RESOURCES.TRACE_ND_STATUS
(
  TDS_ID                   INTEGER              NOT NULL,
  TDS_DN_NUM               VARCHAR2(100 BYTE)   NOT NULL,
  TDS_OLD_STATUS           VARCHAR2(1 BYTE)     NOT NULL,
  TDS_NEW_STATUS           VARCHAR2(1 BYTE)     NOT NULL,
  TDS_ACTION_DATE          DATE                 NOT NULL,
  TDS_OLD_STATUS_MOD_DATE  DATE                 NOT NULL,
  TDS_NEW_STATUS_MOD_DATE  DATE                 NOT NULL,
  TDS_OLD_DN_MODDATE       DATE,
  TDS_NEW_DN_MODDATE       DATE,
  TDS_IP                   VARCHAR2(100 BYTE),
  TDS_USERNAME             VARCHAR2(100 BYTE)   NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;
 
COMMENT ON TABLE RESOURCES.TRACE_ND_STATUS IS 'Permettre de tracer les diff‰rentes modifications de statut de la table DIRECTORY_NUMBER';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_DN_NUM IS 'Numero dÆappel';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_OLD_STATUS IS 'Statut ND avant changement';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_NEW_STATUS IS 'Statut ND aprˆs changement';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_ACTION_DATE IS 'Date de l action';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_OLD_STATUS_MOD_DATE IS 'Ancienne date modification statut';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_NEW_STATUS_MOD_DATE IS 'Nouvelle date modification statut';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_OLD_DN_MODDATE IS 'Ancienne date modification';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_NEW_DN_MODDATE IS 'Nouvelle date modification.';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_IP IS 'Adresse IP';
COMMENT ON COLUMN RESOURCES.TRACE_ND_STATUS.TDS_USERNAME IS 'utilisateur ';
 
CREATE UNIQUE INDEX RESOURCES.PK_TDS_ID ON RESOURCES.TRACE_ND_STATUS
(TDS_ID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16M
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
 
ALTER TABLE RESOURCES.TRACE_ND_STATUS ADD (
  CONSTRAINT PK_TDS_ID
  PRIMARY KEY
  (TDS_ID)
  USING INDEX RESOURCES.PK_TDS_ID
  ENABLE VALIDATE);
 
 
CREATE INDEX RESOURCES.TDS_DN_NUM_INX ON RESOURCES.TRACE_ND_STATUS
(TDS_DN_NUM)
NOLOGGING
TABLESPACE INDX
PCTFREE    20
INITRANS   16
MAXTRANS   255
STORAGE    (
            INITIAL          992M
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
 
CREATE OR REPLACE PUBLIC SYNONYM TRACE_ND_STATUS FOR RESOURCES.TRACE_ND_STATUS;
 
 
GRANT SELECT, UPDATE, DELETE, INSERT ON RESOURCES.TRACE_ND_STATUS TO LIQUI_DML_ROLE; 
GRANT INSERT ON RESOURCES.TRACE_ND_STATUS TO SYSADM; 

CREATE SEQUENCE RESOURCES.TDS_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
GRANT SELECT ON RESOURCES.TDS_ID_SEQ TO LIQUI_DML_ROLE;  
GRANT SELECT ON RESOURCES.TDS_ID_SEQ TO SYSADM;  