COMMENT ON COLUMN NOTIFICATIONS.SENT_FROM  IS '- EMAIL
- SENDER'; 
COMMENT ON COLUMN NOTIFICATIONS.SENT_TO  IS '- EMAIL
- MSISDN'; 
COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_TYPE  IS '- SMS
- EMAIL'; 
COMMENT ON COLUMN NOTIFICATIONS.STATUS  IS '0 : Nouvelle NOTIFICATIONS à traiter
1 : NOTIFICATIONS envoyée avec succès
-1 : NOTIFICATIONS en erreur
';
 
