GRANT SELECT, UPDATE, DELETE, INSERT ON NOTIFICATIONS.NOTIFICATIONS TO LIQUI_DML_ROLE; 
GRANT SELECT ON NOTIFICATIONS_SEQ TO LIQUI_DML_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON NOTIFICATIONS.NOTIFICATIONS_HISTORY TO LIQUI_DML_ROLE; 
GRANT SELECT, UPDATE, DELETE, INSERT ON NOTIFICATIONS.FP_SMS_CID TO LIQUI_DML_ROLE; 