          
CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATIONS FOR NOTIFICATIONS.NOTIFICATIONS;           
           
CREATE SEQUENCE NOTIFICATIONS.NOTIFICATIONS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;          
           
CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATIONS_SEQ FOR NOTIFICATIONS.NOTIFICATIONS_SEQ;

CREATE TABLE NOTIFICATIONS.NOTIFICATIONS_HISTORY 
(   
  ID                 NUMBER NOT NULL,
  NOTIFICATION_TYPE  VARCHAR2(10) NOT NULL,
  CREATED_AT         DATE DEFAULT SYSDATE,
  SENT_AT            DATE,
  SENT_ERROR         VARCHAR2(500),
  SUBJECT            VARCHAR2(500),
  MESSAGE            VARCHAR2(2000),
  STATUS             INTEGER,
  RETRIES            INTEGER,
  SENT_FROM          VARCHAR2(500),
  SENT_TO            VARCHAR2(500),
  ATTACHEMENT        VARCHAR2(2000),
  MIME_TYPE          VARCHAR2(50)
)
TABLESPACE DATA
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            )
LOGGING
NOCACHE
NOPARALLEL;

CREATE OR REPLACE PUBLIC SYNONYM NOTIFICATIONS_HISTORY FOR NOTIFICATIONS.NOTIFICATIONS_HISTORY;  

CREATE TABLE NOTIFICATIONS.FP_SMS_CID
(
  CID          NUMBER,
  SENDER       VARCHAR2(10),
  INSERT_DATE  DATE                             DEFAULT SYSDATE
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM FP_SMS_CID FOR NOTIFICATIONS.FP_SMS_CID;

