CREATE INDEX NOTIFICATIONS.IDX_NOTIFICATIONS_STATUS ON NOTIFICATIONS.NOTIFICATIONS
(STATUS)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );           
           
ALTER TABLE NOTIFICATIONS.NOTIFICATIONS
    ADD (
        CONSTRAINT FK_NOTIFICATION_TYPE CHECK
            (NOTIFICATION_TYPE IN ('EMAIL', 'SMS'))
            ENABLE VALIDATE,
        CONSTRAINT FK_NOTIFICATION_STATUS CHECK
            (STATUS IN (0, 1, -1))
            ENABLE VALIDATE);
                       
 