-- 1. Create the FTP_EXCHANGE user
CREATE USER FTP_EXCHANGE
  IDENTIFIED BY FTP_EXCHANGE
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
 
-- 2. Grant basic role
GRANT CONNECT TO FTP_EXCHANGE;
 
ALTER USER FTP_EXCHANGE DEFAULT ROLE ALL;
 
-- 3. Grant system privileges
GRANT CREATE TABLE TO FTP_EXCHANGE;
 
-- 4. Assign tablespace quotas
ALTER USER FTP_EXCHANGE QUOTA UNLIMITED ON DATA;
 
ALTER USER FTP_EXCHANGE QUOTA UNLIMITED ON INDX;


CREATE TABLE FTP_EXCHANGE.SFTP_SERVER
(
  SERVER_ID     NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 10 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  SERVER_NAME    VARCHAR2(30 BYTE),
  SERVER_HOST   VARCHAR2(100 BYTE)            NOT NULL,
  SERVER_PORT        INTEGER,
  PROTOCOL       VARCHAR2(100 BYTE),
  AUTHTYPE       VARCHAR2(128 BYTE),
  PASSWORD  VARCHAR2(100 BYTE),
  USERNAME        VARCHAR2(128 BYTE),
  AUTHKEY         CLOB
)
LOB ("AUTHKEY") STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   8
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

COMMENT ON TABLE FTP_EXCHANGE.SFTP_SERVER IS 'FTP Server for Files transfert';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.SERVER_ID IS 'FTP Server Identifier';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.SERVER_NAME IS 'SERVER Name to/from it Files will be exchanged';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.SERVER_HOST IS 'Server host name or IP address';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.SERVER_PORT IS 'Server port';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.PROTOCOL IS 'Transfer protocol (SFTP/FTP)';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.AUTHTYPE IS 'Authentication type (passwordless or not)';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.PASSWORD IS 'authetication password';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.USERNAME IS 'authentication user';

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_SERVER.AUTHKEY IS 'authentication key';

CREATE UNIQUE INDEX FTP_EXCHANGE.SFTP_SERVER_PK ON FTP_EXCHANGE.SFTP_SERVER
(SERVER_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE FTP_EXCHANGE.SFTP_SERVER ADD (
  CONSTRAINT SFTP_SERVER_PK
  PRIMARY KEY
  (SERVER_ID)
  USING INDEX FTP_EXCHANGE.SFTP_SERVER_PK
  ENABLE VALIDATE);


--DROP SEQUENCE FTP_EXCHANGE.ISEQ$$_128981;
CREATE OR REPLACE PUBLIC SYNONYM SFTP_SERVER FOR FTP_EXCHANGE.SFTP_SERVER;

--create SFTP_ROUTE table to holde sftp route to be executed
CREATE TABLE FTP_EXCHANGE.SFTP_ROUTE
(
  ROUTE_ID     NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 10 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  SERVER_ID    NUMBER,
  ROUTE_NAME        VARCHAR2(15 BYTE),
  TASK_TYPE_ID NUMBER,
  REMOTE_PATH   VARCHAR2(100 BYTE)  ,
  TEMP_REMOTE_PATH   VARCHAR2(100 BYTE)  ,
  ARCH_REMOTE_PATH  VARCHAR2(100 BYTE)  ,
  LOCAL_PATH   VARCHAR2(100 BYTE)  ,
  SFTP_ACTION       VARCHAR2(3 BYTE),
  FREQUENCY  INTEGER,
  BUCKET         VARCHAR2(100 BYTE),
  MOD               VARCHAR2(2 BYTE)            DEFAULT 'ON'
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   8
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

COMMENT ON COLUMN FTP_EXCHANGE.SFTP_ROUTE.MOD IS 'Pour activer ("ON") où désactiver (OFF) la route';

CREATE UNIQUE INDEX FTP_EXCHANGE.SFTP_ROUTE_PK ON FTP_EXCHANGE.SFTP_ROUTE
(ROUTE_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE FTP_EXCHANGE.SFTP_ROUTE ADD (
  CONSTRAINT SFTP_ROUTE_PK
  PRIMARY KEY
  (ROUTE_ID)
  USING INDEX FTP_EXCHANGE.SFTP_ROUTE_PK
  ENABLE VALIDATE);


ALTER TABLE FTP_EXCHANGE.SFTP_ROUTE ADD (
  FOREIGN KEY (SERVER_ID) 
  REFERENCES FTP_EXCHANGE.SFTP_SERVER (SERVER_ID)
  ENABLE VALIDATE);
  
CREATE OR REPLACE PUBLIC SYNONYM SFTP_ROUTE FOR FTP_EXCHANGE.SFTP_ROUTE;
--create sftp_job table to holde sftp job execution
CREATE TABLE FTP_EXCHANGE.SFTP_JOB
(
  JOB_ID          NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 110 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  ROUTE_ID        NUMBER,
  PRE_SIGNED_URL  VARCHAR2(100 BYTE),
  TASK_ID         NUMBER,
  FILE_NAME       VARCHAR2(100 BYTE),
  MINIO_URL       CLOB,
  START_TIME      TIMESTAMP(6),
  END_TIME        TIMESTAMP(6),
  STATUS          VARCHAR2(100 BYTE),
  ERROR_MESSAGE   VARCHAR2(300 BYTE)
)
LOB (MINIO_URL) STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   8
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX FTP_EXCHANGE.SFTP_JOB_PK ON FTP_EXCHANGE.SFTP_JOB
(JOB_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE FTP_EXCHANGE.SFTP_JOB ADD (
  CONSTRAINT SFTP_JOB_PK
  PRIMARY KEY
  (JOB_ID)
  USING INDEX FTP_EXCHANGE.SFTP_JOB_PK
  ENABLE VALIDATE);


--DROP SEQUENCE FTP_EXCHANGE.ISEQ$$_130405;

-- Sequence ISEQ$$_130405 is created automatically by Oracle for use with an Identity column


CREATE OR REPLACE PUBLIC SYNONYM SFTP_JOB FOR FTP_EXCHANGE.SFTP_JOB;


ALTER TABLE FTP_EXCHANGE.SFTP_JOB ADD (
  FOREIGN KEY (ROUTE_ID) 
  REFERENCES FTP_EXCHANGE.SFTP_ROUTE (ROUTE_ID)
  ENABLE VALIDATE); 
  
CREATE TABLE FTP_EXCHANGE.SFTP_JOB_HIST
(
  JOB_ID     NUMBER NOT NULL,
  ROUTE_ID        NUMBER,
  PRE_SIGNED_URL  VARCHAR2(100 BYTE),
  TASK_ID         NUMBER,
  FILE_NAME       VARCHAR2(100 BYTE),
  MINIO_URL       CLOB,
  START_TIME      TIMESTAMP(6),
  END_TIME        TIMESTAMP(6),
  STATUS          VARCHAR2(100 BYTE),
  ERROR_MESSAGE   VARCHAR2(300 BYTE)
)
LOB ("MINIO_URL") STORE AS SECUREFILE (
  TABLESPACE  DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   8
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;

CREATE OR REPLACE PUBLIC SYNONYM SFTP_JOB_HIST FOR FTP_EXCHANGE.SFTP_JOB_HIST;  