CREATE TABLE EFT.TRANSACTIONS
(
  ID                NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  TRANSACTION_ID    NUMBER,
  TRANSACTION_DATE  DATE,
  AMOUNT            NUMBER,
  ENTRY_DATE        DATE,
  USERNAME          VARCHAR2(38 BYTE),
  RETRY             NUMBER,
  PAYMENT_ID        NUMBER,
  STATUS            NUMBER,
  NATURE            VARCHAR2(38 BYTE),
  MOTIF             VARCHAR2(255 BYTE)
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCACHE;

COMMENT ON COLUMN EFT.TRANSACTIONS.TRANSACTION_ID IS 'Identifiant unique de la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.TRANSACTION_DATE IS 'Date effective de la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.AMOUNT IS 'Montant associé à la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.ENTRY_DATE IS 'Date d’enregistrement de la transaction dans le système';
COMMENT ON COLUMN EFT.TRANSACTIONS.USERNAME IS 'Utilisateur ayant initié ou enregistré la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.RETRY IS 'Nombre de tentatives ou réessais effectués pour cette transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.PAYMENT_ID IS 'Identifiant du paiement associé à la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.STATUS IS 'Statut actuel de la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.NATURE IS 'Nature ou type de la transaction';
COMMENT ON COLUMN EFT.TRANSACTIONS.MOTIF IS 'Motif ou description du traitement de la transaction';



CREATE INDEX TRANSACTIONS.IDX_TRANSACTIONS ON EFT.TRANSACTIONS
(TRANSACTION_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   8
MAXTRANS   255
STORAGE    (
            INITIAL          32K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX TRANSACTIONS.IND_ENTDATE ON EFT.TRANSACTIONS
(ENTRY_DATE)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   8
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM TRANSACTIONS FOR EFT.TRANSACTIONS;

GRANT SELECT, UPDATE, DELETE, INSERT ON EFT.TRANSACTIONS TO LIQUI_DML_ROLE;