CREATE USER EFT IDENTIFIED BY EFT DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO EFT;
GRANT RESOURCE TO EFT;

ALTER USER EFT QUOTA UNLIMITED ON DATA;
ALTER USER EFT QUOTA UNLIMITED ON INDX;





