CREATE USER TRANSACTIONS IDENTIFIED BY TRANSACTIONS DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO TRANSACTIONS;
GRANT RESOURCE TO TRANSACTIONS;

ALTER USER TRANSACTIONS QUOTA UNLIMITED ON DATA;
ALTER USER TRANSACTIONS QUOTA UNLIMITED ON INDX;





