CREATE USER EVENT IDENTIFIED BY EVENT DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO EVENT;
GRANT RESOURCE TO EVENT;

ALTER USER EVENT QUOTA UNLIMITED ON DATA;
ALTER USER EVENT QUOTA UNLIMITED ON INDX;





