CREATE TABLE EVENT.CDC_EVENT
(
		EVENT_ID      NUMBER(38) NOT NULL,
		TOPIC       VARCHAR2(100) NOT NULL,
        PAYLOAD     CLOB NOT NULL,
        SCHEMA_ID   NUMBER,
        ENTRY_DATE  DATE DEFAULT SYSDATE
);

ALTER TABLE EVENT.CDC_EVENT ADD CONSTRAINT PK_EVENT_ID PRIMARY KEY  (EVENT_ID);

CREATE OR REPLACE PUBLIC SYNONYM CDC_EVENT FOR EVENT.CDC_EVENT;

GRANT SELECT, UPDATE, DELETE, INSERT ON EVENT.CDC_EVENT TO LIQUI_DML_ROLE;