CREATE TABLE EVENT.CDC_EVENT_ERROR
(
        CDC_EVENT_ERROR_ID NUMBER(38) NOT NULL,
		EVENT_ID      NUMBER(38) NOT NULL,
		EVENT_CONSUMER_ID NUMBER(38) NOT NULL,
        ERROR_DATE  DATE DEFAULT SYSDATE,
        ERROR_MESSAGE CLOB NOT NULL
);


ALTER TABLE EVENT.CDC_EVENT_ERROR ADD (
    FOREIGN KEY (EVENT_ID)
        REFERENCES EVENT.CDC_EVENT (EVENT_ID)
            ENABLE VALIDATE);

ALTER TABLE EVENT.CDC_EVENT_ERROR ADD (
    FOREIGN KEY (EVENT_CONSUMER_ID)
        REFERENCES EVENT.CDC_EVENT_CONSUMER_AUDIT (EVENT_CONSUMER_ID)
            ENABLE VALIDATE);

ALTER TABLE EVENT.CDC_EVENT_ERROR ADD CONSTRAINT PK_CDC_EVENT_ERROR_ID PRIMARY KEY  (EVENT_ID);

CREATE OR REPLACE PUBLIC SYNONYM CDC_EVENT_ERROR FOR EVENT.CDC_EVENT_ERROR;

GRANT SELECT, UPDATE, DELETE, INSERT ON EVENT.CDC_EVENT_ERROR TO LIQUI_DML_ROLE;