CREATE TABLE EVENT.CDC_EVENT_HIST
(
		EVENT_ID      NUMBER(38) NOT NULL,
		TOPIC       VARCHAR2(100),
        PAYLOAD     CLOB,
        SCHEMA_ID   NUMBER,
        ENTRY_DATE  DATE DEFAULT SYSDATE
);

CREATE OR REPLACE PUBLIC SYNONYM CDC_EVENT_HIST FOR EVENT.CDC_EVENT_HIST;

GRANT SELECT, UPDATE, DELETE, INSERT ON EVENT.CDC_EVENT_HIST TO LIQUI_DML_ROLE;
