CREATE TABLE EVENT.CDC_EVENT_CONSUMER_AUDIT
(
        EVENT_CONSUMER_ID NUMBER(38) NOT NULL,
		EVENT_ID      NUMBER(38) NOT NULL,
		CONSUMED_BY       VARCHAR2(100) NOT NULL,
        CONSUMED_AT  DATE DEFAULT SYSDATE
);

ALTER TABLE EVENT.CDC_EVENT_CONSUMER_AUDIT ADD (
    FOREIGN KEY (EVENT_ID)
        REFERENCES EVENT.CDC_EVENT (EVENT_ID)
            ENABLE VALIDATE);

ALTER TABLE EVENT.CDC_EVENT_CONSUMER_AUDIT ADD CONSTRAINT PK_EVENT_CONSUMER_ID PRIMARY KEY  (EVENT_CONSUMER_ID);

CREATE OR REPLACE PUBLIC SYNONYM CDC_EVENT_CONSUMER_AUDIT FOR EVENT.CDC_EVENT_CONSUMER_AUDIT;

GRANT SELECT, UPDATE, DELETE, INSERT ON EVENT.CDC_EVENT_CONSUMER_AUDIT TO LIQUI_DML_ROLE;